vllm-project/aibrix

pkg/plugins/gateway/algorithms/prefix_cache_and_load.go
pkg/plugins/gateway/gateway.go
pkg/plugins/gateway/prefixcacheindexer/tree.go
pkg/utils/util.go

**NOTE**:  PR #678  should be merged first. Will remove [WIP] in the PR title once PR #678 is merged.
This PR includes a new routing algorithm in gateway. It considers prefix and load together to route requests. 
At high level, the algorithm is 
1. Find the prefix matching in the radix tree for the incoming request
2. Check if the matched prefix has significant length of tokens. For now, the threshold for significant prefix matching  is 50%. In other words, if the matching 
3. If the matched prefix has significant length of tokens, then do prefix-aware routing. Route to the pod that has the longest prefix matching. token length is greater than 50% of the input tokens, then it will do prefix-aware routing.
4. If the matched prefix does not significant length of tokens, then do more …

Prefix and load aware routing with radix tree kv cache

---

docs/source/getting_started/installation/installation.rst
docs/source/getting_started/quickstart.rst

Changed `kubectl apply` to `kubectl create` commands to avoid kubernetes annotation limit.
Resolves: #743 
---
<details>
<ul> …

[Docs]: Fixed kubectl commands for install of components

---

benchmarks/client/client.py

This PR fixes a few bugs in client and also improves failure request handling.
Bugs
- Header setting in AsyncOpenAI was not being done (routing-strategy header)
- It was counting the number of output tokens in a wrong way in streaming client.
Improvement
- Handling failure request in a better way
---
<details>
<p>Your PR title should start with one of these prefixes to indicate the …

[fix] fixing bug in using AsyncOpenAI client (header setting, token counting, etc)

---

.github/workflows/installation-tests.yml
.github/workflows/lint-and-tests.yml

Add integration tests to CI.
xref https://github.com/vllm-project/aibrix/issues/710
---
<details>
<ul> …

[CI] Add integration test 

---

pkg/controller/modeladapter/modeladapter_controller.go
pkg/controller/podautoscaler/podautoscaler_controller.go
pkg/controller/rayclusterfleet/progress.go
pkg/controller/rayclusterfleet/rayclusterfleet_controller.go
pkg/controller/rayclusterreplicaset/rayclusterreplicaset_controller.go
pkg/metadata/users.go
pkg/plugins/gateway/gateway.go
pkg/utils/users.go

---
<details>
<ul>
<li><code>[API]</code>: Modifications to aibrix's API or …

[Bug] fix: correct non-inherited context

---

pkg/cache/cache.go

Ignores worker pods for gateway routing
---
<details>
<ul> …

Ignore worker pods for gateway routing

---

development/vllm/config/deployment.yaml
pkg/plugins/gateway/gateway.go
pkg/plugins/gateway/gateway_test.go
pkg/plugins/gateway/util.go

Make stream include usage as optional parameter. If request is for a user (user has default tpm limit, if not configured) then stream's include usage is mandatory.
Heterogeneous GPU use case is not supported with stream option right now. Once the support is added, include_usage need to be enabled as well.
---
<details>
<p>Your PR title should start with one of these prefixes to …

Make stream include usage as optional

---

Makefile

Install command in makefile installs config/crd objects which are re-installed again in make deploy. Removing redundant command from make install
---
<details>
<ul> …

Remove redundant install crds in makefile

---

pkg/plugins/gateway/util.go

Right now if routing strategy is enabled, then gateway processes request message for prefix cache aware routing. In this case, add "prompt" request input along with "messages". This is patch fix, detailed fix will be done in next iteration.
Resolves: #783
---
<details>
<ul>
<li><code>[Bug]</code>: Corrections to …

Update request message processing for /v1/completion input

---

benchmarks/client/client.py

Improved client code
- Added target_pod in result.
- Made streaming and non-streaming clients consistent in terms of format
Resolves: #798 #796 
---
<details>
<ul> …

Added target pod to client result and made clients consistent

---

.github/workflows/docker-build-images.yml
.github/workflows/docker-push-images.yml
.github/workflows/installation-tests.yml
.github/workflows/lint-and-tests.yml
.github/workflows/python-tests.yml

This is a blocker for release branch testing now. Since we move to fork mode for development, release branch and main branch now are all protected branch. We should enable test against any change on these branches.
Resolves: https://github.com/vllm-project/aibrix/issues/804
---
<details>
<ul>
<li><code>[Bug]</code>: …

Enable CI tests for release branch

---

development/app/README.md

fix vllm mock app Unauthorized response
via: https://github.com/vllm-project/aibrix/blob/main/development/app/config/mock/api-key-patch.yaml#L22
---
<details>
<ul>
<li><code>[API]</code>: Modifications to aibrix's API or …

[Docs]: fix vllm mock app Unauthorized response

---

benchmarks/generator/config/completion-len-config.json
benchmarks/generator/config/examples/completion-len-config.json
benchmarks/generator/config/examples/prompt-len-config.json
benchmarks/generator/config/examples/traffic-config.json
benchmarks/generator/config/predefined/completion-len-configs/HighFast.json
benchmarks/generator/config/predefined/completion-len-configs/HighSlow.json
benchmarks/generator/config/predefined/completion-len-configs/LowFast.json
benchmarks/generator/config/predefined/completion-len-configs/LowSlow.json
benchmarks/generator/config/predefined/prompt-len-configs/HighFast.json
benchmarks/generator/config/predefined/prompt-len-configs/HighSlow.json
benchmarks/generator/config/predefined/prompt-len-configs/LowFast.json
benchmarks/generator/config/predefined/prompt-len-configs/LowSlow.json
benchmarks/generator/config/predefined/traffic-configs/HighFast.json
benchmarks/generator/config/predefined/traffic-configs/HighSlow.json
benchmarks/generator/config/predefined/traffic-configs/LowFast.json
benchmarks/generator/config/predefined/traffic-configs/LowSlow.json
benchmarks/generator/config/prompt-len-config.json
benchmarks/generator/config/traffic-config.json
benchmarks/generator/distribution.py
benchmarks/generator/peak_analysis.py
benchmarks/generator/sample_request.py
benchmarks/generator/utils.py
benchmarks/generator/workload_generator.py

This PR reconfigures workload generator to adopt predefined load types.

Reconfigure workload generator for predefined synthetic patterns

---

pkg/plugins/gateway/algorithms/least_busy_time.go
pkg/plugins/gateway/algorithms/least_kv_cache.go
pkg/plugins/gateway/algorithms/least_latency.go
pkg/plugins/gateway/algorithms/least_request.go
pkg/plugins/gateway/algorithms/prefix_cache.go
pkg/plugins/gateway/algorithms/prefix_cache_and_load.go
pkg/plugins/gateway/algorithms/prefix_cache_test.go
pkg/plugins/gateway/algorithms/random.go
pkg/plugins/gateway/algorithms/throughput.go
pkg/plugins/gateway/prefixcacheindexer/hash.go
test/e2e/routing_strategy_test.go

In this PR: https://github.com/vllm-project/aibrix/pull/810, gateway's router initialization was refactored recently which introduced a bug where routers were re-initialized on each request. Due to re-initialization of prefix cache router was loosing in-memory state and e2e tests were failing.
Resolves: #816
---
<details>
<p>Your PR title should start with one of these prefixes to indicate the nature of the …

Fix repeated initialization of gateway routers and add unit test for prefix cache

---

config/standalone/distributed-inference-controller/kustomization.yaml

We are trying to install the distributed inference by the standalone way "kubectl apply -k config/standalone/distributed-inference-controller/", and currently we should use the v0.2.1 and the special kuberay version to make it work.
---
<details>
<ul>
<li><code>[Bug]</code>: …

Bump AIBrix version to v0.2.1 for standalone distributed inference

---

hack/update-codegen.sh

There is a bug in kube_codegen.sh in the k8s.io/code-generator project. It cannot correctly handle the situation where the path contains soft links. So we should cd to the canonicalized path before generating codes.
Resolves: #853 
---
<details>
<ul> …

[Misc] Resolve symlink ambiguity when generating codes

---

Makefile
README.md
config/dependency/kuberay-operator/kustomization.yaml
config/dependency/kustomization.yaml

Right now `make deploy` command uses `kubectl create` because ray related CRDs size is pretty big to support `kubectl apply`. 
Since envoy proxy CRD is also pretty big and requires `make create`, merging ray CRD with envoyproxy crd for installation such that `make deploy can use kubectl apply`.
---
<details>
<p>Your PR title should start with one of these prefixes to indicate the …

Refactor make deploy to use apply instead of create

---

pkg/plugins/gateway/gateway.go
pkg/plugins/gateway/gateway_req_body.go
pkg/plugins/gateway/gateway_rsp_body.go

Add a flag to enable/disable GPU optimizer tracing. By default it is disabled.
Resolves: 790
---
<details>
<ul> …

Add flag to enable/disable GPU Optimizer tracing

---

benchmarks/client/client.py

Currently when workload file `constant.jsonl` has `model:null`, even if we set default_model in client.py, it will be then use `Model:None/null` and ignore the default_model and throw the error:
```
ERROR:root:Request 2: Error (BadRequestError): Error code: 400 - {'object': 'error', 'message': "[{'type': 'string_type', 'loc': ('body', 'model'), 'msg': 'Input should be a valid string', 'input': None}]", 'type': 'BadRequestError', 'param': None, 'code': 400}
```
With the fix, the client default_model is used in case workload file has `model: null`
```
{"timestamp": 5000, "requests": [{"prompt": "Certainly, here is the
continuation of the agreement:\n\nTHIS AGREEMENT constitutes the entire
agreement between the parties and supersedes all prior negotiations,
...
Authorized Signature]\n[Insert …
```

[Misc] Fix client.py in case workload has model null and client has default_model

---

pkg/controller/kvcache/kvcache_controller.go
pkg/controller/modeladapter/resources_test.go

```go
// FromInt creates an IntOrString object with an int32 value. It is
// your responsibility not to call this method with a value greater
// than int32.
// Deprecated: use FromInt32 instead.
```
---
<details> …

[Misc] Cleanup deprecated function intstr.FromInt

---

pkg/cache/cache_init.go
pkg/plugins/gateway/algorithms/least_busy_time.go
pkg/plugins/gateway/algorithms/least_kv_cache.go
pkg/plugins/gateway/algorithms/least_latency.go
pkg/plugins/gateway/algorithms/least_request.go
pkg/plugins/gateway/algorithms/prefix_cache.go
pkg/plugins/gateway/algorithms/prefix_cache_and_load.go
pkg/plugins/gateway/algorithms/prefix_cache_test.go
pkg/plugins/gateway/algorithms/random.go
pkg/plugins/gateway/algorithms/router.go
pkg/plugins/gateway/algorithms/router_test.go
pkg/plugins/gateway/algorithms/throughput.go
pkg/plugins/gateway/gateway.go
pkg/plugins/gateway/gateway_req_body.go
pkg/plugins/gateway/gateway_test.go
test/e2e/routing_strategy_test.go

Introduced two router Register functions to delay the initialization of routers.
1. RegisterDelayed: this is a more generic function to delay the initialization of routers.
2. RegisterDelayedConstructor: Pass the router constructor and expect the initialization of routers to get delayed until the cache is initialized.
Resolves: #912
---
<details>
<p>Your PR title should start with one of these prefixes to indicate …

[Bug] Routers that require cache failed on Register

---

pkg/controller/modeladapter/scheduling/random.go

we already check in : 
https://github.com/vllm-project/aibrix/blob/d0973764a4e3234bb8b73d18092304909fa59e47/pkg/controller/modeladapter/modeladapter_controller.go#L385-L390
---
<details>
<ul>
<li><code>[Bug]</code>: …

[Misc] chore: remove unnecessary check for pod is zero

---

pkg/controller/kvcache/kvcache_controller.go

When follow the [example](https://aibrix.readthedocs.io/latest/features/distributed-kv-cache.html) to deploy a kvcache on GKE, I saw deepseek pod keeps crashing with error "not found /var/run/vineyard.sock", while the kvcache pod is always pending.
```code
$ kubectl get pod
NAME                                            READY   STATUS             RESTARTS       AGE
deepseek-coder-7b-instruct-688778dd76-wzwmg     0/1     CrashLoopBackOff   13 (68s ago)   65m
deepseek-coder-7b-kvcache-7c984cdff8-xq5pk      0/1     Pending            0              65m
deepseek-coder-7b-kvcache-etcd-0                1/1     Running            0              65m
```
The root cause is 
1.  When creating a GPU node in node pool, GKE automatically adds the nvidia.com/gpu=present:NoSchedule taint to the new …

[Bug] add Tolerations for kvcache pod to fix Pending and CrashLoopBackOff on GKE

---

pkg/controller/kvcache/kvcache_controller.go
pkg/controller/modeladapter/modeladapter_controller.go
pkg/controller/podautoscaler/podautoscaler_controller.go
pkg/controller/rayclusterfleet/rayclusterfleet_controller.go
pkg/controller/rayclusterreplicaset/rayclusterreplicaset_controller.go

Return errors promptly to prevent incorrect log messages and avoid triggering inappropriate goroutine start within the podautoscaler controller.
---
<details>
<ul> …

[BUG] return directly when error occurs while adding the controller

---

pkg/controller/podautoscaler/hpa_resources.go
pkg/controller/podautoscaler/podautoscaler_controller.go

when makeHPA returns nil, it causes a panic.
To fix this, let's modify makeHPA to return an additional error field. That way, following convention, when the error is nil, the HPA won't be nil.
---
<details>
<ul> …

[BUG] controller: fix generating the corresponding HPA object for the PA

---

cmd/controllers/main.go
config/standalone/autoscaler-controller/patch.yaml
config/standalone/distributed-inference-controller/patch.yaml
config/standalone/model-adapter-controller/kustomization.yaml
config/standalone/model-adapter-controller/patch.yaml

Add an option for standalone components installation. After this change, all standalone controller deployment manifest beside lora will have `--disable-webhook`. #930 is one example. 
Resolves: https://github.com/vllm-project/aibrix/issues/932
---
<details>
<ul> …

[CLI] Add —disableWebhook in controller 

---

samples/distributed/fleet-two-node.yaml

Summary
This PR updates the existing RayClusterFleet example for qwen-coder-7b-instruct to make it fully functional for multi-node inference with vLLM and Ray.
What's fixed or added:
Corrected the command and args for the Ray head pod to properly start vllm serve
Explicitly set tensor-parallel-size and distributed-executor-backend
Added the aibrix-runtime sidecar container
Added a missing Service to expose port 8000 (vLLM)
Added an HTTPRoute to route OpenAI-compatible requests via Gateway API
Added the environment variable PYTORCH_CUDA_ALLOC_CONF=expandable_segments:True to handle memory fragmentation
Ensured Ray workers are correctly bootstrapped and terminated
Why this matters
The original example didn't include necessary components like the service or routing layer and lacked Ray-aware …

fix: complete RayClusterFleet example for multi-node vLLM inference

---

pkg/plugins/gateway/gateway_test.go
pkg/plugins/gateway/util.go
pkg/utils/util.go

There's no need to check the environment variables every time a request is processed.
---
<details>
<ul>
<li><code>[CI]</code>: Changes to build …

[Bug] avoid frequent lookup of the routing strategy env

---

cmd/plugins/main.go
config/gateway/gateway-plugin/gateway-plugin.yaml
config/overlays/release/default_patch.yaml
pkg/cache/cache_init.go
pkg/plugins/gateway/gateway.go

Add graceful shutdown for gateway pod and adds liveness/readiness probes.
On termination of gateway pod, no new requests will be accepted and just existing requests will complete.
Resolves: #760  #906 
---
<details>
<ul>
<li><code>[CI]</code>: Changes to …

Add graceful shutdown for gateway and add liveness/readiness probes

---

benchmarks/generator/workload-generator/README.md
benchmarks/generator/workload-generator/utils.py
benchmarks/generator/workload-generator/workload_generator.py

Change all output file names to workload (workload.jsonl and workload.pdf) for easy adoption in benchmark script. 
Related: #903

[Fix] Unify all workload generator output file names

---

benchmarks/client/utils.py

This PR fixes shallow copy errors in prompt history. 
#903

[Fix] Fix shallowcopy error in prompt history retrieval

---

benchmarks/client/client.py

This PR fixes a task dispatch ordering issue by assiging requests from the same session to the same worker thread. This ensures requests from the same session are dispatched and processed in its intended order. 
#903

Assign tasks to client by keys

---

pkg/plugins/gateway/gateway.go
test/e2e/e2e_test.go
test/e2e/util.go

- Use a custom transport with disabled keep-alives and caching
- Add protection for for context.canceld and EOF case
- Early return the 401 resposne
- Update e2e SDK with timeout
Resolves: https://github.com/vllm-project/aibrix/issues/1004
---
<details>
<ul> …

[Fix] 401 errors in gateway should be returned as immediate response 

---

.github/workflows/installation-tests.yml
.github/workflows/lint-and-tests.yml
development/app/config/templates/deployment/deployment.yaml
test/e2e/model_adapter_test.go
test/e2e/util.go

In model adapter e2e test, one pod is deleted to validate lora adapter is rescheduled. In mock app deployment config, readiness probe interval was 10s and before pod could be running other tests run which can affect them negatively (one of them is prefix cache validation).
This change
- reduces the readiness probe for mock app.
- add validation in model adapter test to ensure all pods are running in post test.
Resolves: #951 
---
<details>
<h3>Pull …

E2E CI fix to ensure all pods are ready

---

pkg/cache/cache_api.go
pkg/cache/cache_impl.go
pkg/cache/cache_init.go
pkg/cache/cache_log.go
pkg/cache/cache_metrics.go
pkg/cache/cache_test.go
pkg/cache/cache_trace.go
pkg/cache/informers.go
pkg/cache/model.go
pkg/controller/modeladapter/scheduling/bin_pack.go
pkg/controller/modeladapter/scheduling/least_adapters.go
pkg/controller/modeladapter/scheduling/least_latency.go
pkg/controller/modeladapter/scheduling/least_throughput.go
pkg/plugins/gateway/algorithms/least_busy_time.go
pkg/plugins/gateway/algorithms/least_kv_cache.go
pkg/plugins/gateway/algorithms/least_latency.go
pkg/plugins/gateway/algorithms/least_request.go
pkg/plugins/gateway/algorithms/throughput.go
pkg/plugins/gateway/algorithms/vtc/vtc_basic.go
pkg/plugins/gateway/algorithms/vtc/vtc_test.go
pkg/utils/pod.go

Previously, the metaPods cache used only the `name` as the key, which could lead to 
key collisions when Pods with the same name existed in different namespaces. 
This pr updates cache to use `namespace/name` as the key, ensuring uniqueness 
and avoiding potential conflicts. This aligns with Kubernetes' common practice of 
using `namespace/name` to uniquely identify resources.
Resolves: https://github.com/vllm-project/aibrix/issues/1008
---
<details>
<p>We appreciate your contribution to aibrix! To ensure a smooth review process and …

[Bug] fix: update metaPods cache to use namespace/name as the key

---

test/e2e/routing_strategy_test.go
test/e2e/vtc_routing_test.go

Now we use a more formal way to validate the randomness of the random routing result in the e2e test. The chi-squared test is used. A non-random distribution will reject the null hypothesis.  We use a low significance level to be more error tolerant and keep a small (100) repeats.
Resolves: #1021 
---
<details>
<ul> …

[BUG] Use more accurate chi-squared test for randomness validation in e2e test.

---

python/aibrix_kvcache/aibrix_kvcache/l2/placement/__init__.py
python/aibrix_kvcache/aibrix_kvcache/l2/placement/placement.py
python/aibrix_kvcache/aibrix_kvcache/l2/placement/simple_placement.py
python/aibrix_kvcache/aibrix_kvcache/meta_service/__init__.py
python/aibrix_kvcache/aibrix_kvcache/meta_service/meta_service.py
python/aibrix_kvcache/aibrix_kvcache/meta_service/redis_meta_service.py
python/aibrix_kvcache/tests/conftest.py
python/aibrix_kvcache/tests/test_placement.py

This PR includes facilities to support L2Cache's cluster mode.
- meta service module
- placement module
- Unit test for placement and meta service
Meta service module has the same architectural level as L2Cache since it could be further extended to support more functionalities beyond current placement feature used by L2Cache.
---
<details>
<p>Your PR title should start with one of …

[Feature] AIBrix KVCache L2Cache Part2

---

python/aibrix_kvcache/aibrix_kvcache/l2/l2_cache.py

Change L2Cache's register descriptor container to list to support unhashable descriptors.
---
<details>
<ul> …

[Fix] Fix L2Cache's register descriptor container

---

cmd/kvcache-watcher/main.go
config/manager/manager.yaml
config/rbac/controller-manager/role.yaml
config/standalone/kv-cache-controller/patch.yaml
pkg/controller/kvcache/backends/common.go
pkg/controller/kvcache/backends/distributed.go
pkg/controller/kvcache/backends/distributed_test.go
pkg/controller/kvcache/backends/hpkv.go
pkg/controller/kvcache/backends/infinistore.go
pkg/controller/kvcache/backends/reconciler.go
pkg/controller/kvcache/kvcache_controller.go

1. Update key from `hpkv_nodes` to `hpkv_cluster_metadata` based on internal sync up result
2. Support sa/role/rolebinding for watcher pod. We used to specific a fixed service account name and require user to create it and use it. Now, service account is fully managed by controllers. 
3. `make manifest` to generate latest role. I notice customresource is to kubebuilder market in last PR https://github.com/vllm-project/aibrix/pull/922, I added this back.
4. remove fixed `k8s.volcengine.com/pod-networks` setting. Only if user specific volcano engine rdma devices, we will attach this annotation
---
<details>
<summary><strong>Contribution Guidelines …

Support watcher pod rbac in kvcache controller

---

go.mod
pkg/metrics/custom_metrics.go
pkg/metrics/custom_metrics_test.go
pkg/metrics/metrics.go
pkg/plugins/gateway/algorithms/vtc/vtc_basic.go
pkg/plugins/gateway/algorithms/vtc/vtc_basic_test.go

This change adds:
- `vtc_bucket_size_active` custom metric gauge to see if any config change is needed in `vtc-basic`
-  centralized metrics utility for custom metrics like the above in this project
https://github.com/vllm-project/aibrix/pull/1011#issuecomment-2845795519

[MISC]: add vtc_bucket_size_active metric gauge for vtc-basic 

---

api/orchestration/v1alpha1/rayclusterfleet_types.go
pkg/client/applyconfiguration/orchestration/v1alpha1/rayclusterfleetstatus.go
pkg/controller/rayclusterfleet/rollback.go
pkg/controller/rayclusterfleet/sync.go
pkg/controller/rayclusterfleet/util/fleet.go

1. add +kubebuilder:subresource:scale above RayClusterFleet definition
2. add HPAPodSelector field in RayClusterFleetStatus to specify which pods belong to this RayClusterFleet
3. add "aibrix.ai/raycluster-fleet-name" in pod labels
Resolves: #986 
---
<details>
<ul> …

[Bug]fix: add scale subresource to rayclusterfleet

---

benchmarks/client/client.py
benchmarks/generator/dataset_generator/multiturn_prefix_sharing_dataset.py
benchmarks/generator/workload_generator/sample_request.py
benchmarks/generator/workload_generator/utils.py

The `logger.warn()` method is deprecated since Python2.7 and replaced with `logger.warning()`. It leads to those warnings:
```python
DeprecationWarning: The 'warn' method is deprecated, use 'warning' instead
```

Modernize logger interface

---

config/default/kustomization.yaml
config/dependency/kuberay-operator/kustomization.yaml

This PR ensures all container images are explicitly specified in the Kustomize manifests. 
When deploying AIBrix, it’s important to note that the AIBrix mirror is mainly hosted on Dockerhub, and deploying it in environments has Dockerhub access limitation can be challenging. This PR is necessary due to the current lack of proxy support in Helm (to be supported in 0.4.0). 
By fully qualifying all image names, developers can more easily replace or mirror images as needed for local deployment.
Resolves: #1164

[Bug] Fix image replacements in Kustomize files to support installation

---

config/samples/autoscaling_v1alpha1_mock_llama.yaml
development/app/config/heterogeneous/simulator_a40/patch_podautoscaler_a40.yaml
development/app/config/simulator/patch_podautoscaler_a100.yaml
development/app/config/templates/podautoscaler/podautoscaler_apa.yaml
development/app/config/templates/podautoscaler/podautoscaler_kpa.yaml
samples/autoscaling/optimizer-kpa.yaml
samples/heterogeneous/deepseek-coder-7b-l20-podautoscaler.yaml
samples/heterogeneous/deepseek-coder-7b-v100-podautoscaler.yaml

Due to possible implementation changes, some autoscaling configuration examples used the legacy approach, which placed autoscaling parameters under the label section. This PR scans the whole repository and fixes misconfigurations.
Resolves: #1159 
---
<details>
<ul> …

[Bug]: Fix legacy misconfigurations of autoscaling annotations.

---

Makefile
benchmarks/scenarios/gateway/README.md
development/README.md
development/tutorials/podautoscaler/README.md

…guide
It seems that the development instructions were using prvious `make` commands not reflecting the current state of the `Makefile`. In particular, all the commands related to the build/push of the components have been updated, as well as the way to pass a custom docker registry namespace
Resolves: N/A
---
<details> …

[Docs] update development instructions to new make commands

---

docs/source/features/gateway-plugins.rst
docs/source/getting_started/installation/advanced-k8s-examples.rst
docs/source/getting_started/installation/installation.rst

Add comprehensive documentation for deploying AIBrix on Kubernetes with persistent model caching, security policies, and monitoring integration. Includes YAML examples for namespace, deployment, service, and PVC configuration with detailed usage notes.
---
<details>
<ul> …

[Docs]: add advanced kubernetes deployment examples

---

cmd/controllers/main.go
config/standalone/stormservice-controller/kustomization.yaml
config/standalone/stormservice-controller/patch.yaml

Support standalone stormservice deployment

---

docs/source/conf.py
docs/source/index.rst

Resolves: part of #1231 
---
<details>
<ul> …

[Docs]refactor: change architecture to stand-alone directories

---

PROJECT
cmd/controllers/main.go
config/webhook/manifests.yaml
pkg/controller/kvcache/kvcache_controller.go
pkg/controller/kvcache/kvcache_controller_ginkgo_test.go
pkg/controller/kvcache/kvcache_controller_test.go
pkg/utils/kvcache.go
pkg/utils/kvcache_test.go
pkg/webhook/kvcache_webhook.go
test/integration/webhook/kvcache_webhook_test.go
test/integration/webhook/suit_test.go

[Misc] feature: use kvcache webhook

---

pkg/controller/roleset/roleset_controller.go
pkg/controller/stormservice/stormservice_controller.go

https://github.com/Jeffwan/aibrix/pull/new/jiaxin/update-stormservice-stability
1min reconcile time is too long and sometime we have to wait long time for deletion done. This is to reduce the reconcile time at this moment. this mainly affects the deletion experiences
Resolves: part of https://github.com/vllm-project/aibrix/issues/1252
---
<details>
<p>Your PR title should start with one of these prefixes to indicate …

Update stormservice controller DefaultRequeueAfter to 15s

---

pkg/controller/roleset/roleset_controller.go
pkg/controller/stormservice/stormservice_controller.go

Use domain-qualified finalizer name to avoid potential conflicts.
```
I0706 07:33:29.414963       1 warning_handler.go:65] "msg"="metadata.finalizers: \"stormservice-finalizer\": prefer a domain-qualified finalizer name to avoid accidental conflicts with other finalizer writers" "logger"="KubeAPIWarningLogger"
```
Resolves: https://github.com/vllm-project/aibrix/issues/1254
---
<details> …

[Misc] Use domain-qualified finalizer name

---

pkg/controller/roleset/rolesyncer_test.go

Increase the unit test coverage of rolesyncer, for now only stateless rolesyncer.
Minor change to stateless rolesyncer.
Resolves: #1263 
---
<details>
<ul> …

[Misc] Add unit test code coverage of rolesyncer

---

benchmarks/benchmark.py

This PR adds help message to benchmark script.

Adding help flag to benchmark script 

---

python/aibrix_kvcache/.pre-commit-config.yaml
python/aibrix_kvcache/aibrix_kvcache/envs.py
python/aibrix_kvcache/aibrix_kvcache/l2/connectors/connector.py
python/aibrix_kvcache/aibrix_kvcache/l2/connectors/pris.py
python/aibrix_kvcache/requirements/core.txt

Add Pris Connector
---
<details>
<ul> …

[Feature] KVCache: add Pris connector

---

.github/workflows/docker-build-images.yml
.github/workflows/docker-push-images.yml

Support arm and multi-arch build
1. use multi-arch in docker-push-images.yaml.
2. upgrade docker/setup-buildx-action from `v2` to `v3`
3. use buildx action for individual build jobs instead of our make command
Note: it takes longer time to build and push both amd64 and arm64 images. this is ok. In our PR workflow, we still use make command. Slow post-submit jobs won't affect development experiences.
Resolves: https://github.com/vllm-project/aibrix/issues/1089
---
<details>
<p>We appreciate your contribution to aibrix! To ensure a smooth review process and maintain high code quality, please adhere to the …

[CI] Support multi-arch build in main branch

---

pkg/controller/stormservice/sync.go
pkg/controller/stormservice/sync_test.go
pkg/controller/stormservice/utils.go

While adding tests to `pkg/controller/stormservice/sync_test.go` I noticed that currently the headless service sync logic only handles creation of new services without properly updating existing ones. This PR enhances the sync logic to handle both creation and updates, ensuring service properties (Type, Selector, ClusterIP) stay properly synchronized. Added comprehensive unit tests to verify both scenarios.
Resolves: NONE
---
<details>
<h3>Pull …

[Misc] enhance headless service sync with update logic

---

config/features/vllm-remote-tokenizer/README.md
config/features/vllm-remote-tokenizer/gateway-plugins-env-patch.yaml
config/features/vllm-remote-tokenizer/kustomization.yaml
pkg/apis/constants/labels.go
pkg/cache/cache_metrics.go
pkg/plugins/gateway/algorithms/prefix_cache.go
pkg/plugins/gateway/algorithms/tokenizer_pool.go
pkg/plugins/gateway/algorithms/tokenizer_pool_test.go
pkg/utils/util.go

This PR introduces support for vLLM remote tokenizers that can leverage the tokenization capabilities directly from vLLM engine instances. This feature enables more
accurate tokenization by using the same tokenizer as the serving engine, ensuring consistency between token counting and actual model processing.
- **Tokenizer Consistency**: Using the same tokenizer as the vLLM engine ensures accurate token counting for routing decisions
- **Model-Specific Tokenization**: Different models may use different tokenizers - this feature automatically uses the correct tokenizer for each model
- **Dynamic Scaling**: Remote tokenizers can scale with the vLLM instances, eliminating the need to maintain separate tokenizer deployments
- Added `TokenizerPool` for managing model-specific remote tokenizers …

feat: add vLLM remote tokenizer with engine integration

---

samples/disaggregation/vllm/README.md
samples/disaggregation/vllm/disagg_proxy_server.py

current https://github.com/vllm-project/vllm/blob/main/examples/others/lmcache/disagg_prefill_lmcache_v1/disagg_proxy_server.py doesn't accept the list and it's hard to test xPyD performance with AIBrix router.
---
<details>
<ul> …

[bench] Add vLLM disagg_proxy_server.py with xPyD Support

---

pkg/plugins/gateway/algorithms/prefix_cache.go

This PR fixes a logic bug in the `getTargetPodOnLoadImbalance` function that was causing intermittent test failures when running with the Go race detector.
Fixes intermittent failures in `Test_ValidatePrePrefixMatchLoadBalance` when running `make test-race-condition`.
The bug had two issues:
1. **Incorrect min/max calculation**: The code used `else if` instead of separate `if` statements, preventing proper initialization when the first value should update both min and max.
2. **Potential panic**: When `targetPods` slice was empty (due to the faulty min/max logic), accessing `targetPods[rand.Intn(len(targetPods))]` would panic.
1. Changed the min/max calculation logic from:
```go
if value <= minValue {
minValue = value
} else if value > maxValue {  // BUG: else if prevents both from …
```

[fix] Fix logic bug in prefix cache load balancing causing race test failures

---

docs/source/getting_started/quickstart.rst
samples/quickstart/pd-model.yaml

added pd deployment and curl example in the quickstart doc.
- used official vllm:v0.9.1 image and PyNcclConnector provided by vllm pd example.
Resolves: #[[1375]](https://github.com/vllm-project/aibrix/issues/1375)
---
<details>
<ul> …

[Docs] add pd-model deployment example in quickstart doc

---

README.md

Very minor mistake in release date in README.md. [v0.1.0](https://github.com/vllm-project/aibrix/releases/tag/v0.1.0) is release in 2024 and not 2025.

doc: correct release date in README.md

---

pkg/controller/stormservice/sync.go
pkg/controller/stormservice/sync_test.go

The StormService controller currently creates a headless Service without setting its ownerReference.
As a result, when a StormService resource is deleted, the associated headless Service is not automatically cleaned up and remains in the cluster.
This change ensures that the created headless Service has the correct ownerReference so it will be garbage-collected when the StormService is deleted.
---
<details> …

[Bug] stormservice's headless service not set ownerRef

---

python/aibrix_kvcache/aibrix_kvcache/metrics.py

[Bug] KVCache: fix metrics

---

pkg/plugins/gateway/algorithms/pd_disaggregation.go
pkg/plugins/gateway/algorithms/pd_disaggregation_test.go
pkg/plugins/gateway/gateway_req_body.go
pkg/plugins/gateway/gateway_req_body_test.go

- Add kv_transfer_params configuration to prefill requests and decode requests
this is a follow up PR of #1425, to address the problems in https://github.com/vllm-project/aibrix/issues/1407
```
python3 benchmark_serving.py --port 8000 --host 192.168.0.138  --seed $(date +%s) \
>       --model qwen3-8B \
>       --tokenizer /models/Qwen3-8B \
>       --dataset-name random --random-input-len 8000 --random-output-len 200 \
>       --num-prompts 200 --burstiness 100 --request-rate 1 --metric-percentiles 95 \
>       --backend openai-chat --endpoint /v1/chat/completions --ignore-eos
```
1st try - without the change - aibrix router
```
Traffic request rate: 1.0 RPS.
Burstiness factor: 100.0 (Gamma distribution)
Maximum request concurrency: None …
```

Fix P/D disaggregation router to follow Nixl kv_transfer_params

---

docs/source/getting_started/installation/installation.rst

Force user to use helm and make it required
Resolves: https://github.com/vllm-project/aibrix/issues/1460
---
<details>
<ul> …

[Docs] Update helm installation guidance

---

Makefile
test/integration/controller/suit_test.go

we should build the framework first, which can effectively reduce the cost of integration. Later we can even split different controller tasks.
part of: 
https://github.com/vllm-project/aibrix/issues/1430
---
<details>
<p>Your PR title should start with one of these prefixes to indicate the nature of the …

[Test]: add controller integration test framework

---

benchmarks/benchmark.py
benchmarks/config.yaml

This PR fixes missing traffic_pattern parameters in benchmark script
Resolves: #1470

Fix missing traffic_pattern parameters in benchmark script

---

cmd/controllers/main.go

- prevent duplicate registration of `orchestrationv1alpha1.AddToScheme`
---
<details>
<ul> …

refactor(scheme): prevent duplicate registration in RegisterSchemas

---

api/orchestration/v1alpha1/roleset_types.go
api/orchestration/v1alpha1/zz_generated.deepcopy.go
config/crd/orchestration/orchestration.aibrix.ai_rolesets.yaml
config/crd/orchestration/orchestration.aibrix.ai_stormservices.yaml
pkg/controller/roleset/rolling.go
pkg/controller/roleset/utils.go
pkg/controller/roleset/utils_test.go
test/integration/webhook/stormservice_webhook_test.go

Support role upgrade sequences in stormservice
Resolves: #1292
---
<details>
<ul> …

Feat: Support role upgrade sequences in stormservice

---

pkg/controller/roleset/podset_rollsyncer.go

Fix the mismatch issue
The issue was template mutation caused by shared object references:
1. Multiple PodSets were sharing the same `role.Template` object reference
2. When `injectContainerEnvVars` modified containers in one PodSet, it was mutating the shared template
3. This caused subsequent PodSets to compute hashes from the already-modified template
4. Result: PodSet labels used the original hash, but environment variables used hashes from modified templates
```
kubectl get podsets -o json | jq -r '
.items[] |
.metadata.name as $name |
.metadata.labels["role-template-hash"] as $label |
(.spec.template.spec.containers[]?.env[]? | select(.name=="ROLE_TEMPLATE_HASH") | .value) as $env |
"\($name): label=\($label), env=\($env)"'
llm-xpyd-roleset-8plg2-decode-76647b8d65-0: …
```

[fix] deep copy template to avoid hash mutation issue

---

pkg/controller/podset/podset_controller.go
pkg/controller/roleset/utils.go

[Misc]: ignore AlreadyExists and NotFound in controller operations

---

observability/grafana/AIBrix_vLLM_Engine_Dashboard.json

Fix incorrect expressions for *mean* TTFT and TPOP in Grafana, which have been defined in reverse.
---
<details>
<ul>
<li><code>[Docs]</code>: Updates …

[Misc] Fix incorrect expressions for mean TTFT and TPOP in Grafana

---

docs/source/development/development.rst
docs/source/development/release.rst
docs/source/getting_started/faq.rst
test/README.md

- Update test guidance in both test folder and official docs
- Update development.rst structure
Resolves: follow up of https://github.com/vllm-project/aibrix/issues/1430
---
<details>
<ul> …

[Docs] Add development test guidance

---

pkg/webhook/deployment_webhook.go

[Bug]: fix annotation in deployment webhook

---

python/aibrix_kvcache/aibrix_kvcache/__init__.py
python/aibrix_kvcache/aibrix_kvcache/cache_handle.py
python/aibrix_kvcache/aibrix_kvcache/cache_manager.py
python/aibrix_kvcache/aibrix_kvcache/memory/allocator.py
python/aibrix_kvcache/aibrix_kvcache/memory/external_memory_region.py
python/aibrix_kvcache/aibrix_kvcache/memory/memory_region.py
python/aibrix_kvcache/requirements/test.txt
python/aibrix_kvcache/tests/test_cache_manager.py

- ExternalMemoryRegion supports customized callback which will be invoked on MR release
- Enable external cache handle support on both L1 and L2 caches
- NOTE: Need to use NCLD layout if using different block sizes for engine kvcache and AIBrix kvcache
---
<details>
<ul> …

[Feature] KVCache: support external cache handle

---

python/aibrix/aibrix/downloader/__main__.py
python/aibrix/aibrix/downloader/base.py
python/aibrix/aibrix/downloader/entity.py
python/aibrix/aibrix/downloader/huggingface.py
python/aibrix/aibrix/downloader/s3.py
python/aibrix/aibrix/downloader/tos.py

- S3 listing now uses paginator and returns all keys under the prefix recursively.
-Threadpool path now raises worker errors by calling future.result() after wait.
- HF token never logged; token shows as <redacted> if present.
- TOS v2 no longer sets empty aws_access_key_id/aws_secret_access_key, preserving default credential chain/IRSA.
---
<details> …

Improve the runtime downloader quality

---

test/integration/controller/suit_test.go

it's my bad. I want to rebase a change and merge this one without waiting for test pass
---
<details>
<ul> …

[Bug] add the return value check to pass linter

---

pkg/plugins/gateway/algorithms/fallback_test.go

Add unit test for FallbackRouter
- Test fallback to routing algorithms (throughput, latency, gpu-cache, kv-cache)
- Test mixed pod readiness states and edge conditions  
- Test large pod lists and pods without IPs
- Add 2 additional SetFallback method test cases
- Test nil provider handling and sequential SetFallback calls
a part of https://github.com/vllm-project/aibrix/issues/1485
Tests:

[Misc] Add tests for FallbackRouter

---

pkg/controller/podautoscaler/aggregation/aggregator.go
pkg/controller/podautoscaler/algorithm/algorithm.go
pkg/controller/podautoscaler/algorithm/apa.go
pkg/controller/podautoscaler/algorithm/hpa.go
pkg/controller/podautoscaler/algorithm/kpa.go
pkg/controller/podautoscaler/autoscaler.go
pkg/controller/podautoscaler/config/extractor.go
pkg/controller/podautoscaler/metrics/client.go

```
DefaultAutoScaler (thread-safe)
├── factory (immutable)
├── client (immutable)
├── metricsClient (thread-safe with mutex)
├── aggregator (stateless)
└── algorithmCache (RWMutex)
├── KPA instance (stateless empty struct)
├── APA instance (stateless empty struct)
└── HPA instance (stateless empty struct)
```
Resolves: #1422
---
<details>
<p>Your PR title should start with one of these prefixes to indicate the …

Resolve the UpdateConfiguration race issue in autoscaler

---

benchmarks/benchmark.py
benchmarks/client/client.py
benchmarks/config.yaml

* Added support to set client duration limit in seconds for benchmark execution, allowing cancellation of requests after the specified time.
* Added support to set client max concurrent sessions to control the number of active sessions during benchmarking.
Initial motivation was to fix issue that in the end of the benchmark, if the benchmark was too slow, it would dispatch all pending requests in the end of the benchmark, making it strange plots for those cases, it was behaving as expected until 16:28, then it and dispatched bursts of pending requests and not predictable:
This was due to the behavior of send all requests according to the workload schedule and then waiting for all requests to complete, which may not provide a predictable client behaviour.
Using parameters …

[Misc] Benchmark: add duration limit and max concurrent sessions settings to client
