vllm-project/aibrix

benchmarks/client/client.py
In client, it records failed requests as well.
client: `benchmark/client/client.py`
---
<details>
<ul> …
=> Recording failed requests in benchmark client

README.md
thanks @gaocegege for pointing out the issue
---
<details>
<ul> …
=> Fix slack link in README.md

README.md
The license link is broken. This is to fix it.
=> [readme] Fix wrong link

python/aibrix/aibrix/batch/scheduler.py
Alway -> Always
---
<details>
<ul>
<li><code>[CLI]</code>: Changes or additions to the Command Line Interface</li>
<li><code>[Misc]</code>: For …
=> [Misc] update scheduler.py

pkg/plugins/gateway/algorithms/prefix_cache_and_load.go, pkg/plugins/gateway/prefixcacheindexer/tree.go
Made it more thread safe especially regarding accessing TreeNode data structure.
Made variables of TreeNode private and made all them accessed through Getter functions.
---
<details>
<ul> …
=> Improve thread safety for TreeNode data structure and refactor related codes

api/orchestration/v1alpha1/kvcache_types.go
Address comment: https://github.com/vllm-project/aibrix/pull/713/files#r1968603515
---
<details>
<ul> …
=> Fix CacheSpec api scheme

README.md
=> docs: Fix link to license

SECURITY.md
Create SECURITY.md to include initial security policy with contact information
---
<details>
<ul> …
=> Create SECURITY.md to enable security policy

development/app/Makefile
Allow setting:
- `CONTAINER_TOOL=podman`
- `AIBRIX_CONTAINER_REGISTRY_NAMESPACE=my-registry.com/xyz`
Variables names follow the main (root dir) Makefile
---
<details>
<ul>
<li><code>[API]</code>: Modifications to aibrix's …
=> [Misc] Parametrize Makefile for mocked vLLM apps

config/dependency/kuberay-operator/README.md, config/dependency/kuberay-operator/templates/deployment.yaml
fix env error caused by helm set command, use —set-string for env bool. It will keep inject the probs which cause failures for large models.
Resolves: https://github.com/vllm-project/aibrix/issues/777
---
<details>
<ul>
<li><code>[CI]</code>: Changes to …
=> Disable ENABLE_PROBES_INJECTION in correct way

.github/workflows/docker-build-images.yml, .github/workflows/docker-push-images.yml, .github/workflows/installation-tests.yml, .github/workflows/lint-and-tests.yml, .github/workflows/python-tests.yml
Enable tests for release branch
---
<details>
<ul> …
=> cherry-pick Enable CI tests for release branch (#805)

.github/workflows/installation-tests.yml, config/dependency/kuberay-operator/README.md, config/dependency/kuberay-operator/templates/deployment.yaml, development/app/requirements.txt, development/tutorials/distributed/fleet.yaml, development/vllm/config/deployment.yaml, pkg/cache/cache.go, pkg/controller/podautoscaler/podautoscaler_controller.go, pkg/plugins/gateway/gateway.go, pkg/plugins/gateway/gateway_test.go, pkg/plugins/gateway/util.go
Cherry pick #776 #779 #788 #789 #794 to release branch
---
<details>
<ul> …
=> Cherry pick #776 #779 #788 #789 #794 to release branch

benchmarks/client/client.py, benchmarks/generator/sample_request.py, benchmarks/generator/workload_generator.py
To support workload generator / client that uses per request model. Remove model dependency from client.
=> [Misc] Adding model field to each request

cmd/plugins/main.go, pkg/plugins/gateway/algorithms/least_busy_time.go, pkg/plugins/gateway/algorithms/least_kv_cache.go, pkg/plugins/gateway/algorithms/least_latency.go, pkg/plugins/gateway/algorithms/least_request.go, pkg/plugins/gateway/algorithms/prefix_cache.go, pkg/plugins/gateway/algorithms/prefix_cache_and_load.go, pkg/plugins/gateway/algorithms/random.go, pkg/plugins/gateway/algorithms/router.go, pkg/plugins/gateway/algorithms/throughput.go, pkg/plugins/gateway/algorithms/util.go, pkg/plugins/gateway/gateway.go, pkg/plugins/gateway/gateway_ratelimit.go, pkg/plugins/gateway/gateway_req_body.go, pkg/plugins/gateway/gateway_req_headers.go, pkg/plugins/gateway/gateway_rsp_body.go, pkg/plugins/gateway/gateway_rsp_headers.go, pkg/plugins/gateway/gateway_test.go, pkg/plugins/gateway/types.go, pkg/plugins/gateway/util.go
refactor gateway-plugins ext-proc server codebase
---
<details>
<ul>
<li><code>[API]</code>: Modifications to aibrix's …
=> [Refactor]: gateway-plugins ext-proc server codebase

.github/workflows/release-build.yaml
CI: update release tags pattern(more precisely), prevent trigger release workflow wrongly.
---
<details>
<ul> …
=> [CI]: update release tags pattern

docs/source/getting_started/installation/lambda.rst
Fix the paths in lambda cloud doc
Resolves: N/A
---
<details>
<ul>
<li><code>[API]</code>: Modifications to aibrix's …
=> Fix the paths in lambda cloud doc

samples/quickstart/model.yaml
Added startup probe to deal with slow cold-start model container in example model.
Resolves: #772 
---
<details>
<ul> …
=> [Bug] Added Startup Probe in Quickstart Model

config/gateway/gateway.yaml
Increases default envoy proxy cpu/memory: 100m/512Mi -> 1000m/1Gi and increases client buffer size from 1MB to 4MB. These are default settings, users can update it for their usecase.
---
<details>
<ul> …
=> Increase envoy proxy memory config and client connection buffersize

pkg/controller/modelrouter/modelrouter_controller.go
HTTPRoute is missing for RayClusterFleet, We need this to be compatible with openai sdk, otherwise user have to specify the routing strategy custom header by themselves
Resolves: https://github.com/vllm-project/aibrix/issues/827, part of https://github.com/vllm-project/aibrix/issues/758
---
<details>
<ul> …
=> Support to create default HttpRoute for RayClusterFleet

.github/workflows/docker-push-images.yml, config/gateway/gateway.yaml, pkg/controller/modelrouter/modelrouter_controller.go
for patch release
---
<details>
<ul> …
=> cherry-pick #825 #826 part of #717 in release branch

README.md, benchmarks/autoscaling/7b.yaml, benchmarks/autoscaling/deepseek-llm-7b-chat/deploy.yaml, benchmarks/gateway/7b.yaml, config/overlays/release/kustomization.yaml, config/overlays/vke-dev/gateway-plugin/kustomization.yaml, config/overlays/vke-dev/gpu-optimizer/kustomization.yaml, config/overlays/vke-dev/manager/kustomization.yaml, config/overlays/vke-ipv4/default/kustomization.yaml, config/overlays/vke/default/kustomization.yaml, docs/source/development/release.rst, docs/source/getting_started/installation/installation.rst, docs/source/getting_started/installation/lambda.rst, docs/source/getting_started/quickstart.rst, python/aibrix/pyproject.toml, samples/adapter/base-api-key.yaml, samples/adapter/base.yaml, samples/heterogeneous/deepseek-coder-7b-l20-deployment.yaml, samples/heterogeneous/deepseek-coder-7b-v100-deployment.yaml
this PR is for release only.
---
<details>
<ul> …
=> Update version and tags to v0.2.1

.github/workflows/release-build.yaml
it’s my careless cherry-pick #717. I only make part of change and forgot the release-build updates.
---
<details>
<ul>
<li><code>[Docs]</code>: …
=> Disable Github Container Registry build & push in release workflow

.github/workflows/installation-tests.yml, pkg/controller/modelrouter/modelrouter_controller.go, pkg/controller/rayclusterfleet/rayclusterfleet_controller.go
1. Fix integration test trigger issue missing from earlier PR
2. Fix some log format issue and remove unnecessary logs
---
<details>
<ul> …
=> [Misc] Fix CI issue on release branch and clean up logs

README.md, benchmarks/autoscaling/deepseek-llm-7b-chat/deploy.yaml, benchmarks/gateway/7b.yaml, config/overlays/release/kustomization.yaml, config/overlays/vke-dev/manager/kustomization.yaml, config/overlays/vke-ipv4/default/kustomization.yaml, config/overlays/vke/default/kustomization.yaml, docs/source/development/release.rst, docs/source/getting_started/installation/installation.rst, docs/source/getting_started/installation/lambda.rst, docs/source/getting_started/quickstart.rst, python/aibrix/pyproject.toml, samples/adapter/base-api-key.yaml, samples/adapter/base.yaml, samples/heterogeneous/deepseek-coder-7b-l20-deployment.yaml, samples/heterogeneous/deepseek-coder-7b-v100-deployment.yaml
This is for v0.2.1 release
---
<details>
<ul> …
=> Bump AIBrix version to v0.2.1 in manifests

docs/source/community/community.rst
Fix dead link
Resolves:  #830 
---
<details>
<ul>
<li><code>[CLI]</code>: Changes or additions to the Command Line Interface</li> …
=> [Docs] Update Slack link

docs/source/features/heterogeneous-gpu.rst
Remove repeated line in docs.
---
<details>
<ul> …
=> [Docs] Remove repeated lines

pkg/metadata/handlers.go, pkg/metadata/model.go, pkg/metadata/model_test.go
Follow up of #802, build OpenAI style response
---
<details>
<ul> …
=> Support OpenAI api style /v1/models response

pkg/plugins/gateway/algorithms/least_busy_time.go, pkg/plugins/gateway/algorithms/least_kv_cache.go, pkg/plugins/gateway/algorithms/least_latency.go, pkg/plugins/gateway/algorithms/least_request.go, pkg/plugins/gateway/algorithms/prefix_cache.go, pkg/plugins/gateway/algorithms/prefix_cache_and_load.go, pkg/plugins/gateway/algorithms/prefix_cache_test.go, pkg/plugins/gateway/algorithms/random.go, pkg/plugins/gateway/algorithms/router.go, pkg/plugins/gateway/algorithms/router_test.go, pkg/plugins/gateway/algorithms/throughput.go, pkg/plugins/gateway/gateway.go, pkg/plugins/gateway/gateway_req_body.go, pkg/plugins/gateway/prefixcacheindexer/tree.go
Some minor clean up
---
<details>
<ul> …
=> Introduce RoutingContext in Route interface and clean up stale codes

pkg/controller/podautoscaler/podautoscaler_controller.go
Add status updating to podAutoScaler controller to sync hpa status to podAutoScaler.
Implement one TODO in podautoscaler_controller.
---
<details>
<ul> …
=> [Misc]: sync hpa status to podAutoScaler

benchmarks/client/analyze.py, benchmarks/client/client.py, benchmarks/generator/README.md, benchmarks/generator/distribution.py, benchmarks/generator/generate_realistic_prefix_share_workload.py, benchmarks/generator/sample_request.py, benchmarks/generator/synthetic_prefix_sharing_dataset.py, benchmarks/generator/utils.py, benchmarks/generator/workload_generator.py
This branch lets workload generator to generate workload based on prefix shared synthetic data
Resolves: #813
=> Generate workload based on prefix sharing synthetic data

docs/source/features/runtime.rst
typo fix
no
---
<details>
<ul> …
=> [Docs] fix typo in runtime feature page

development/app/config/mock/components.yaml
chore: clean-up mock yaml #877
<details>
<ul>
<li><code>[CLI]</code>: Changes or additions to the Command Line Interface</li>
<li><code>[Misc]</code>: …
=> chore: clean-up mock yaml

benchmarks/generator/utils.py
Fixes bug on https://github.com/vllm-project/aibrix/blob/f04226adfdf9a53a10cef4fed33b63b4b3600196/benchmarks/generator/utils.py#L231  of when using os.path.dirname(output_path) following the example
```
export TARGET_QPS=1
python workload_generator.py --prompt-file $SHAREGPT_FILE_PATH --interval-ms 1000 --duration-ms 300000 --target-qps $TARGET_QPS --trace-type constant --model "Qwen/Qwen2.5-Coder-7B-Instruct" --output-dir "output" --output-format jsonl
```
Error is empty:
```
File "/Users/ronaldo/github/ronaldosaheki/aibrix/benchmarks/generator/workload_generator.py", line 458, in <module>
plot_workload(
~~~~~~~~~~~~~^
workload_name = workload_name,
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
workload = workload,
^^^^^^^^^^^^^^^^^^^^
bin_size_sec = int(args.interval_ms/1000), …
```
=> [Misc] Fix plot_workload to pass dirname to makedirs

benchmarks/generator/workload_generator.py
This PR adds options to add input/output token length distribution while generating constant workload.
=> [WIP] Adding input/output distribution argument to constant load generator

README.md
- This PR fixes the broken link to the contributing guidelines in README.md.
---
<details>
<ul> …
=> [Docs] Fix broken contributing guidelines link in README

hack/lambda-cloud/install.sh
The `kubectl` and `kind` commands are installed in `~/.local/bin/,` but the path is not included in the PATH environment variable, which results in the system not being able to find the commands.
```bash
> ls  ~/.local/bin/
kubectl  nvkind
> kubectl
Command 'kubectl' not found, but can be installed with:
> nvkind
nvkind: command not found
```
---
<details>
<p>Your PR title should …
=> [Bug] fix install script PATH environment variable

docs/source/features/lora-dynamic-loading.rst
Currently the link from `VLLM_ALLOW_RUNTIME_LORA_UPDATING` points to a non-existing page. With this PR, it now points to https://docs.vllm.ai/en/stable/features/lora.html#dynamically-serving-lora-adapters
None
---
<details>
<ul> …
=> [Docs] Link to dynamic lora from docs

pkg/controller/kvcache/kvcache_controller.go
Adding antiaffinity in kvcache crd as temporary solution to spread the kvcache pods
Resolves: #864 
related issue: #863 
---
<details>
<ul>
<li><code>[Docs]</code>: Updates or additions …
=> Added antiaffinity in kvcache crd

docs/source/features/gateway-plugins.rst
Fix the "tpm" and "rpm" typo in gateway-plugins.rst
---
<details>
<ul>
<li><code>[CLI]</code>: Changes or additions to the Command Line Interface</li> …
=> [Docs] Fix tpm and rpm typo in gateway-plugins.rst

pkg/utils/labels.go
Remove unused function in pkg/utils
---
<details>
<ul>
<li><code>[Docs]</code>: …
=> [Misc] Remove unused function in pkg/utils

benchmarks/client/client.py, benchmarks/generator/sample_request.py, benchmarks/generator/workload_generator.py
This PR removes model name from the workload generator and client.
=> Remove model name from client and generator

config/overlays/release/default_patch.yaml, config/overlays/release/dependency_patch.yaml, config/overlays/release/kustomization.yaml
Add release overlay for production deployment. In this PR, it adds patch to update resources envoy proxy and gateway-plugins pod.
Resolves: #847
---
<details>
<ul> …
=> Add release overlays to update control plane config for production deployment

pkg/controller/rayclusterreplicaset/rayclusterreplicaset_controller.go
This PR improves the `scaleDown`: 
1. Add a concurrency limit to avoid overwhelming during deletions.
2. Aggregate errors 
Resolves: #[Insert issue number(s)] None
---
<details>
<ul> …
=> [Misc] chore(raycluster): add concurrency limit and error aggregation to scaleDown

benchmarks/client/client.py
This PR resolves clien-side bottleneck issue by initializing parallel AsyncOpenAI client. 
- Spawning requests using thread pool.
- Adding timeout and retry config to clients
=> Enable parallel client using thread pool in benchmark client

pkg/cache/cache_impl.go, pkg/cache/cache_trace.go, pkg/cache/pod.go, pkg/metrics/metrics.go
This PR is an example of adding real-time pod stats: running requests. The real-time stat is synced to the metric store for reading.
---
<details>
<ul>
<li><code>[Docs]</code>: Updates …
=> [Misc] Add pods stats example: running requests.

cmd/controllers/main.go, pkg/config/config.go, pkg/controller/modeladapter/modeladapter_controller.go
Resolves: #[Insert issue number(s)] https://github.com/vllm-project/aibrix/issues/911
---
<details>
<ul> …
=> [CLI] feature(modeladapter): make modeladapter controller scheduler policy be configured

pkg/utils/sync_map.go, pkg/utils/sync_map_test.go
Fixed a bug that util.SyncMap.store failed to update the value if the value exists.
Added missing methods in sync.Map such as Swap, CompareAndSwap, and CompareAndDelete.
---
<details>
<ul> …
=> [Bug] Syncmap.Store does not update.

benchmarks/client/client.py
This PR moves benchmark client's delay to each worker thread. Task queue size limited.
=> Move delays to threads in benchmark

cmd/controllers/main.go, pkg/controller/controller.go, pkg/controller/rayclusterfleet/rayclusterfleet_controller.go, pkg/controller/rayclusterreplicaset/rayclusterreplicaset_controller.go
base on: https://github.com/vllm-project/aibrix/pull/940#discussion_r2031322178
---
<details>
<ul>
<li><code>[CI]</code>: Changes to build process …
=> [Misc]: move crd check in Initialize part

pkg/controller/modelrouter/modelrouter_controller.go
The informer's delete function needs to handle the case where the argument is DeletedFinalStateUnknown obj, and asserting it directly will cause a panic.
---
<details>
<ul>
<li><code>[Bug]</code>: Corrections to …
=> [BUG] controller: handle DeletedFinalStateUnknown by the delete func

pkg/controller/modeladapter/utils.go, pkg/controller/modeladapter/utils_test.go, pkg/controller/podautoscaler/metrics/utils.go, pkg/utils/redis.go, pkg/utils/util.go
The project contains some duplicated functions related to environment variables. Remove and consolidate these functions.
---
<details>
<ul> …
=> [Misc] remove the duplicated env functions

config/manager/manager.yaml
Increase the memory limit for the controller manager deployment to prevent OOM errors in most scenarios.
The original value was 256Mi. Doubling it seems like a reasonable size. We can always adjust it further based on more feedback in the future.
Resolves: https://github.com/vllm-project/aibrix/issues/936
---
<details> …
=> [Misc] increase the memory limit of the controller-manager

pkg/cache/cache_metrics.go
- add help func for get Env value
Resolves: None
---
<details>
<ul> …
=> chore: add help func for get Env value

cmd/controllers/main.go, config/standalone/kv-cache-controller/kustomization.yaml, config/standalone/kv-cache-controller/patch.yaml, docs/source/getting_started/installation/installation.rst
Provide the standalone component for KV Cache orchestration.
Resolves: sub-task of https://github.com/vllm-project/aibrix/issues/928
---
<details>
<ul>
<li><code>[Docs]</code>: Updates …
=> Enable standalone installation of kv-cache-controller

build/container/Dockerfile.runtime
Fix the upstream CI issue. there's a Dockerfile change in upstream leads to this issue.  Check below links for more details
Resolves: https://github.com/vllm-project/aibrix/issues/959
---
<details>
<ul>
<li><code>[CI]</code>: Changes to build process or …
=> [fix] Fix wheel build errors in runtime image

benchmarks/generator/workload-generator/sample_request.py, benchmarks/generator/workload-generator/workload_generator.py
This PR adds a knob to control maximum concurrent session sent by the client given a workload.  Large max_concurrent_session means less cache hit.
=> Control maximum concurrent session for workload generator

benchmarks/generator/workload-generator/utils.py
Updating plotting script to visualize cache sharing patterns
=> Updating Plotting Script to Visualize Sharing Patterns

benchmarks/generator/dataset-generator/synthetic_prefix_sharing_dataset.py
This PR changes synthetic cache sharing data to use session id.
=> Change synthetic cache sharing dataset format

pkg/controller/modelrouter/modelrouter_controller.go
Reference grant gives permission to httproute (created in aibrix-system namespace) to route traffic based off k8s service in user namespace. There is one reference grant created per namespace which is shared by all model deployments in that namespace.
Right now, if deployment is deleted then its httproute and reference grant is deleted. Since reference grant is shared by all model deployments in one namespace, this PR ensure that reference grant be deleted only if there are no more model deployments.
---
<details>
<p>We appreciate your contribution to aibrix! To ensure a …
=> [Bug] prevent reference grant delete if shared by other deployments

cmd/plugins/main.go, config/rbac/gateway/role_gateway.yaml, pkg/plugins/gateway/gateway.go, pkg/plugins/gateway/gateway_rsp_headers.go, test/e2e/routing_strategy_test.go
if error on processing response headers, add HTTPRoute status check. There are two scenarios,
1) HTTPRoute is missing
2) HTTProute status is not **_True_**
Resolves: #778 
---
<details>
<ul> …
=> Add httproute status check for response header errors

test/e2e/model_adapter_test.go, test/e2e/routing_strategy_test.go, test/e2e/util.go
=> [Misc] chore: use t.Log instead of Println

benchmarks/client/analyze.py
This PR handles error in output.jsonl in client analysis script.
=> [fix] Handle error output in analysis script

cmd/controllers/main.go, pkg/webhook/modeladapter_webhook.go, test/integration/webhook/suit_test.go
Add readyz check for asynchronously set up webhook
---
<details>
<ul> …
=> cmd/controllers: add readyz check for the webhook

benchmarks/client/analyze.py, benchmarks/client/client.py, benchmarks/generator/workload-generator/README.md, benchmarks/generator/workload-generator/sample_request.py, benchmarks/generator/workload-generator/utils.py, benchmarks/generator/workload-generator/workload_generator.py
This PR fixes bugs in workload generator and client benchmarking a non-sessioned (plain) dataset
#903
=> Bug fix generating plain data format

pkg/cache/informers.go
Adding a handler function after starting the informer may cause the Store to not be initialized in time 
Of course I'm not entirely sure if this causes https://github.com/vllm-project/aibrix/issues/951#issuecomment-2787533355 
but making sure that the initialization of the Store data is done in `initCacheInformers` seems like a better way to go about it
---
<details>
<p>We appreciate your contribution to aibrix! To ensure a smooth review process and maintain high code quality, please adhere to the …
=> [BUG] cache: start informer after adding the resource handler

pkg/utils/redis.go, python/aibrix/aibrix/gpu_optimizer/app.py
=> Update add redis pass for client

pkg/plugins/gateway/gateway.go
=> [Misc] chore: refactor selectTargetPod func

pkg/plugins/gateway/gateway_req_body.go, pkg/types/router_context.go
=> [Misc] chore: remove unuse func

pkg/utils/redis.go
Move this code snippet from package level to method level, then it won't print those misleading logs
Resolves: #995
---
<details>
<ul> …
=> [Misc] Move redis load_env to method level

config/default/kustomization.yaml, config/gateway/kustomization.yaml, config/gpu-optimizer/kustomization.yaml, config/manager/kustomization.yaml, config/metadata/kustomization.yaml, config/rbac/autoscaling/kustomization.yaml, config/rbac/controller-manager/kustomization.yaml, config/rbac/gateway/kustomization.yaml, config/rbac/kustomization.yaml, config/rbac/model/kustomization.yaml, config/rbac/orchestration/kustomization.yaml, config/standalone/autoscaler-controller/kustomization.yaml, config/standalone/distributed-inference-controller/kustomization.yaml, config/standalone/kv-cache-controller/kustomization.yaml, config/standalone/model-adapter-controller/kustomization.yaml
part of v0.3.0 release
Resolves: https://github.com/vllm-project/aibrix/issues/1007
---
<details>
<ul> …
=> [Misc] Add app.kubernetes.io/name labels to components

.github/workflows/docker-build-images.yml, .github/workflows/docker-push-images.yml
To test docker push for multi-arch, adding support for manual trigger.
---
<details>
<ul> …
=> Allow manual trigger for build/push docker images

benchmarks/benchmark.sh, benchmarks/client/README.md, benchmarks/client/client.py, benchmarks/config/base.sh
This PR enables adjustable client pool size and output token limit to control
- Maximum Parallelizable Client
- Maximum token limit supported by client
=> Enabling adjustable client pool size and output token limit

pkg/plugins/gateway/algorithms/least_busy_time.go, pkg/plugins/gateway/algorithms/least_kv_cache.go, pkg/plugins/gateway/algorithms/least_latency.go, pkg/plugins/gateway/algorithms/least_request.go, pkg/plugins/gateway/algorithms/prefix_cache.go, pkg/plugins/gateway/algorithms/prefix_cache_and_load.go, pkg/plugins/gateway/algorithms/random.go, pkg/plugins/gateway/algorithms/router.go, pkg/plugins/gateway/algorithms/throughput.go, pkg/plugins/gateway/algorithms/util.go, pkg/plugins/gateway/algorithms/vtc/vtc_basic.go, pkg/plugins/gateway/algorithms/vtc/vtc_basic_test.go, pkg/types/router.go
=> [Misc] fix: Optimizing Route method of the gateway algorithms

docs/source/getting_started/installation/aws.rst, docs/source/getting_started/installation/gcp.rst, docs/source/getting_started/installation/installation.rst, docs/source/getting_started/installation/lambda.rst, docs/source/getting_started/installation/mac-for-desktop.rst, docs/source/getting_started/quickstart.rst, hack/lambda-cloud/install.sh
- Fix curl script display issue in quickstart and image display bug in lambda page
- Support minikube on Lambda cloud
- Add AWS page and rename GCP page
Resolves: https://github.com/vllm-project/aibrix/issues/644 and https://github.com/vllm-project/aibrix/issues/658
---
<details>
<ul>
<li><code>[Bug]</code>: Corrections …
=> [Docs] Support minikube on Lambda cloud and add AWS page

benchmarks/client/client.py, benchmarks/generator/workload-generator/workload_generator.py
This PR 
- Fix a bug  in workload generator where QPS is not reflected on the generated workload. 
- Fix start time time measurement in client
=> [Fix] Bug fix  for constant workload QPS

.github/workflows/installation-tests.yml, hack/ci/kind-config.yaml
Improve e2e time for installation test
1. builds vllm-mock image in parallel (saves 2mins)
2. add github action to setup go (saves 2 mins)
Overall saving is around ~4mins.
---
<details>
<ul> …
=> Improve installlation test e2e time

pkg/cache/trace_test.go, pkg/controller/util/expectation/expectation.go, pkg/metrics/utils.go, pkg/plugins/gateway/algorithms/prefix_cache_test.go, pkg/utils/redis.go, pkg/utils/sync_map.go, pkg/utils/tokenizer/tiktoken.go
This pr replaces the use of a regular `int32` variable with `atomic.Int32` type to ensure safe concurrent access across multiple goroutines. 
Resolves: None
---
<details>
<ul> …
=> use atomic.Int32c instead of use Int32 type

benchmarks/benchmark.sh, benchmarks/client/README.md, benchmarks/client/client.py, benchmarks/config/base.sh
This PR adds a --time-scale factor to benchmark client for the ease of rate adjustment from the client side during the benchmark process.
=> Adding interval scaling factor for client

pkg/controller/podautoscaler/scaler/apa.go, pkg/controller/podautoscaler/scaler/kpa.go
Resolves: None
---
<details>
<ul> …
=> [Bug] fix: use RLock() instead of Lock() when reading var

benchmarks/generator/dataset-generator/README.md, benchmarks/generator/dataset-generator/utility.py
This PR updates dataset generator's missing argument.
Resolves: #1040
=> Dataset generator output argument fix

config/experimentals/gpu-optimizer/gateway-plugin/kustomization.yaml, config/experimentals/gpu-optimizer/kustomization.yaml, config/gateway/gateway-plugin/gateway-plugin.yaml, docs/source/features/heterogeneous-gpu.rst
GPU Optimizer is experimental and is planned to improve stability. This PR reflects the current status of GPU optimizer and add new "experimentals" config folder to help user enable this feature.
Resolves: #1014 
---
<details>
<ul> …
=> [Docs] Document gpu optimizer as experimental and improve deployment config.

python/aibrix_kvcache/aibrix_kvcache/__init__.py, python/aibrix_kvcache/aibrix_kvcache/envs.py, python/aibrix_kvcache/aibrix_kvcache/l1/__init__.py, python/aibrix_kvcache/aibrix_kvcache/l1/eviction_policy/__init__.py, python/aibrix_kvcache/aibrix_kvcache/l1/eviction_policy/base_eviction_policy.py, python/aibrix_kvcache/aibrix_kvcache/l1/eviction_policy/fifo.py, python/aibrix_kvcache/aibrix_kvcache/l1/eviction_policy/lru.py, python/aibrix_kvcache/aibrix_kvcache/l1/eviction_policy/s3fifo.py, python/aibrix_kvcache/aibrix_kvcache/l1/l1_cache.py, python/aibrix_kvcache/aibrix_kvcache/metrics.py, python/aibrix_kvcache/aibrix_kvcache/utils.py, python/aibrix_kvcache/tests/test_eviction_policies.py, python/aibrix_kvcache/tests/test_l1cache.py
This PR includes L1Cache and common facilities such as envs, metrics and utils.
- L1Cache module: eviction policies (LRU/FIFO/S3FIFO) and L1Cache
- envs/metrics/utils
- Unit tests for eviction policies and L1Cache
---
<details>
<ul> …
=> [Feature] AIBrix KVCache L1Cache

config/manager/manager.yaml, docs/source/index.rst, docs/source/production/observability.rst, observability/grafana/AIBrix_Control_Plane_Runtime_Dashboard.json, observability/grafana/AIBrix_Envoy_Gateway_Dashboard.json, observability/grafana/AIBrix_vLLM_Engine_Dashboard.json, observability/monitor/envoy_metrics_service.yaml, observability/monitor/service_monitor_controller_manager.yaml, observability/monitor/service_monitor_gateway.yaml, observability/monitor/service_monitor_vllm.yaml
Add dashboard and monitoring setup steps for control plane
Resolves: #1405 #84
---
<details>
<ul> …
=> Add dashboard and monitoring setup steps for control plane

pkg/controller/podautoscaler/metrics/utils.go
add more info for pod metric fetch failures in GetMetricsFromPods
- If we fail to get metrics from some pods, we should log a warning message.
- If we fail to get metrics from all pods, we should return an error.
Resolves: https://github.com/vllm-project/aibrix/issues/1032
---
<details>
<p>Your PR title should start with one of these prefixes to …
=> [Bug] fix: add more info for pod metric fetch failures in GetMetricsFromPods

python/aibrix_kvcache/integration/vllm/vllm_v0.8.5-aibrix-kvcache.patch
This PR includes the integration patch for using AIBrix KVCache in vLLLM v0.8.5.
---
<details>
<ul> …
=> [Integration] vLLM integration patch for AIBrix KVCache

cmd/metadata/main.go, cmd/plugins/main.go, test/e2e/vtc_routing_test.go
Resolves: None
---
<details>
<ul> …
=> [Misc] fix: add miss Close() for redis client

cmd/kvcache-watcher/main.go, pkg/controller/kvcache/backends/hpkv.go, pkg/controller/kvcache/backends/infinistore.go
This PR is to enable some metrics for kv cache watcher pod
Resolves: part of #845 
---
<details>
<ul> …
=> Support prometheus metrics in kv watcher pod

python/aibrix_kvcache/integration/vllm/vllm_v0.8.5-aibrix-kvcache.patch
- remove unnecessary dependencies
- `AIBrixOffloadingConnector` supports preempted requests
---
<details>
<ul> …
=> [Integration] Update vLLM integration

config/overlays/release/kustomization.yaml, config/overlays/vke/default/kustomization.yaml, config/standalone/distributed-inference-controller/kustomization.yaml, python/aibrix/pyproject.toml, python/aibrix_kvcache/pyproject.toml
Update python manifest to use non-conflict version number
---
<details>
<ul> …
=> Cut v0.3.0-rc.1 release

.github/workflows/release-build.yaml, python/aibrix/pyproject.toml
=> [fix] Correct the python build path in same step

.github/workflows/release-build.yaml, python/aibrix/pyproject.toml, python/aibrix_kvcache/pyproject.toml
=> [Misc] Skip attaching python artifacts to github release

pkg/controller/modeladapter/modeladapter_controller.go, pkg/utils/raycluster.go
Resolves: https://github.com/vllm-project/aibrix/issues/1052
---
<details>
<ul> …
=> [Bug] fix: condition nil panic in FindStatusCondition func

.github/workflows/release-arm-build.yaml
Bug fix, to rename tag from git.sha to git tag.
Resolves: #1089
---
<details>
<ul> …
=> Upload arm build images with git.ref_name

README.md, benchmarks/scenarios/ps-experiment/README.md, config/gateway/gateway-plugin/gateway-plugin.yaml, config/gateway/gateway.yaml, config/overlays/release/envoy_proxy_patch.yaml, config/overlays/release/gateway_plugins_patch.yaml, docs/source/development/development.rst, docs/source/features/gateway-plugins.rst, docs/source/getting_started/installation/installation.rst, docs/source/getting_started/installation/mac-for-desktop.rst, docs/source/getting_started/quickstart.rst, pkg/plugins/gateway/types.go
- Add openai sdk samples along with multiturn scenario.
- Minor updates for documentation
- Patch updates for envoy_proxy.
- Move PDB config from dev setup to release overlay.
---
<details>
<ul> …
=> Update documentation and add openai sdk samples

docs/source/features/gateway-plugins.rst, pkg/plugins/gateway/algorithms/prefix_cache_and_load.go
---
<details>
<ul>
<li><code>[API]</code>: Modifications to aibrix's API or …
=> Rename preble based prefix routing strategy

python/aibrix_kvcache/integration/vllm/vllm_v0.8.5-aibrix-kvcache.patch
- update vLLM integration
---
<details>
<ul>
<li><code>[API]</code>: Modifications …
=> [Integration] KVCache: update vLLM integration

python/aibrix_kvcache/aibrix_kvcache/cache_manager.py, python/aibrix_kvcache/aibrix_kvcache/envs.py, python/aibrix_kvcache/aibrix_kvcache/l2/connectors/connector.py, python/aibrix_kvcache/aibrix_kvcache/l2/connectors/hpkv.py, python/aibrix_kvcache/aibrix_kvcache/l2/connectors/infinistore.py, python/aibrix_kvcache/aibrix_kvcache/l2/connectors/mock.py, python/aibrix_kvcache/aibrix_kvcache/l2/l2_cache.py, python/aibrix_kvcache/aibrix_kvcache/l2/placement/placement.py, python/aibrix_kvcache/aibrix_kvcache/memory/allocator.py, python/aibrix_kvcache/aibrix_kvcache/status.py
- InfiniStore connector supports hint_gid_index
- Fix kvcache placement and memory registration in cluster mode
---
<details>
<ul> …
=> [Feature] KVCache: Suppport InfiniStore GID and enhance cluster mode

config/crd/orchestration/orchestration.aibrix.ai_rayclusterfleets.yaml
- regenerate crd for: https://github.com/vllm-project/aibrix/pull/1082/files
---
<details>
<ul> …
=> [Chore] fix: regenerate crd

config/overlays/release/kustomization.yaml, config/overlays/vke/default/kustomization.yaml, config/standalone/distributed-inference-controller/kustomization.yaml, python/aibrix/pyproject.toml, python/aibrix_kvcache/pyproject.toml, samples/volcano-engine/README.md, samples/volcano-engine/deepseek-8b-kv-cluster.yaml, samples/volcano-engine/deepseek-8b-kv-direct.yaml, samples/volcano-engine/deepseek-8b-kv-dram.yaml, samples/volcano-engine/deepseek-8b-naive.yaml, samples/volcano-engine/deepseek-r1.yaml, samples/volcano-engine/kvcache.yaml
last rc release
---
<details>
<ul> …
=> Bump version to v0.3.0-rc.2

config/overlays/release/gateway_plugins_patch.yaml, config/overlays/release/kustomization.yaml, config/overlays/release/pdb.yaml, python/aibrix/pyproject.toml, python/aibrix_kvcache/pyproject.toml
Address https://github.com/vllm-project/aibrix/issues/1116
---
<details>
<ul> …
=> [Fix] Move pdb from patch to resources

docs/source/features/distributed-kvcache-and-cross-engine-kv-reuse.rst, docs/source/features/kvcache-offloading-framework.rst
- format KVCache docs to eliminate warnings
---
<details>
<ul> …
=> [Docs] format KVCache docs to eliminate warnings

.github/workflows/release-arm-build.yaml
Previously, release build would only push linux/arm64 which would overwrite any previous images with same tag. With this image, it will push for all platforms.
Resolves: #1120 
---
<details>
<ul> …
=> Update multi-arch image push to include all platforms for release

benchmarks/README.md, benchmarks/benchmark.py, benchmarks/config.yaml, docs/source/features/benchmark-and-generator.rst
This PR addresses remaining comments in #999
=> [Docs] Addressing benchmark doc comments

python/aibrix/pyproject.toml, python/aibrix_kvcache/pyproject.toml
=> Bump python project version to v0.3.0

README.md
Fixed the typo forthe  installation command
=> [Docs] Update typo for installation command

README.md
=> [Bug]: fix: README.md docs install error

pkg/cache/informers.go
Currently, when the gateway restarts, it only syncs the models already deployed. The adapters are not synced in the cache, which causes a model not found while trying the inference. 
This code resynchronizes the active model adapters at the start of the gateway pod.
---
=> Resync model adapters on gateway restart

samples/volcano-engine/README.md
- Add code symbols after backticks
- Remove a private OPENAI_API_KEY, which may cause risks to the api-key owner
- Fix grammar issues
---
<details>
<ul>
<li><code>[API]</code>: Modifications to aibrix's API or …
=> [Doc] Improve samples/volcano-engine/README.md

pkg/cache/cache_init.go, pkg/cache/cache_metrics.go, pkg/metrics/utils.go, pkg/metrics/utils_test.go
1. Introduce a worker pool in Store initialization to handle pod metrics updates
2. Adjust `updatePodMetrics` method to utilize the job channel for distributing work among workers
3. use context timeouts to prevent hanging operations.
Resolves: part of https://github.com/vllm-project/aibrix/issues/970
---
<details> …
=> feature: use worker pool management for periodic metrics update

development/app/config/templates/deployment/deployment.yaml, development/vllm/macos/deployment.yaml, pkg/types/router_context.go, pkg/utils/pod.go, pkg/utils/pod_test.go
Resolves: #1111 
---
<details>
<ul> …
=> Add support for custom inference engine port

.github/.testcoverage.yml, .github/workflows/lint-and-tests.yml
=> Add unit test code coverage

python/aibrix_kvcache/aibrix_kvcache/common/object_pool.py, python/aibrix_kvcache/tests/test_common.py
Resolves: None
---
<details>
<ul> …
=> [Bug]: fix(aibrix kvcache): ObjectPool 

pkg/controller/controller.go
If we just want to check if the crd exists, we don't need to get the full crd information. Usually, the crd information is bigger, so it is enough to get the ObjectMetadata information.
```bash
// PartialObjectMetadata is a generic representation of any object with ObjectMeta. It allows clients
// to get access to a particular ObjectMeta schema without knowing the details of the version.
// +k8s:deepcopy-gen:interfaces=k8s.io/apimachinery/pkg/runtime.Object
type PartialObjectMetadata struct {
TypeMeta `json:",inline"`
// Standard object's metadata.
// More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#metadata
// +optional
ObjectMeta `json:"metadata,omitempty" protobuf:"bytes,1,opt,name=metadata"`
}
``` …
=> Enhance the CRD existence check

python/aibrix/tests/test_metrics.py
Resolves: None
- add unit test for aibrix metrics collector
---
<details>
<ul> …
=> [Misc]: add unit test for aibrix metrics collector

docs/source/getting_started/quickstart.rst
Add vllm-cpu local deployment guide to Quickstart
Resolves: #785 
---
<details>
<ul> …
=> [Docs] Add vllm-cpu local deployment guide to Quickstart

benchmarks/scenarios/gateway/README.md
=> fix: gateway benchmark info

pkg/plugins/gateway/util.go, pkg/plugins/gateway/util_test.go
AiBrix will raise an error when parse complex content in completion body
error message:
```
/v1/chat/completions json unmarhsal valid messages with complex content%!(EXTRA string=/v1/chat/completions json unmarhsal valid messages with complex content)
```
request body:
```
{"model": "llama2-7b", "messages": [{"role": "system", "content": "this is system"},{"role": "user", "content": [{"type": "text", "text": "say this is test"}, {"type": "text", "text": "say this is test"}]}]}
```
---
<details>
<p>We appreciate your contribution to aibrix! To ensure a smooth review …
=> [Bug] fix: error when parse complex content in completion body

.github/.testcoverage.yml, .github/workflows/lint-and-tests.yml, Makefile, pkg/cache/trace_test.go, pkg/types/types_test.go, pkg/utils/prefixcacheindexer/tree_test.go, pkg/utils/utils_test.go
=> Add race condition check in unit-test CI and add test-coverage cmd in Makefile

benchmarks/README.md, benchmarks/benchmark.py, benchmarks/client/client.py, benchmarks/client/utils.py, benchmarks/config.yaml, benchmarks/generator/dataset_generator/synthetic_prefix_sharing_dataset.py, benchmarks/generator/dataset_generator/synthetic_prompt.py, benchmarks/generator/workload_generator/README.md, benchmarks/generator/workload_generator/utils.py, benchmarks/generator/workload_generator/workload_generator.py, docs/source/features/benchmark-and-generator.rst
This PR supports [Mooncake traces](https://github.com/kvcache-ai/Mooncake/tree/main/FAST25-release/traces) in workload generator.
=> Supporting Mooncake Traces in Workload Generator

benchmarks/client/client.py, benchmarks/client/utils.py
Revert client changes pushed by error
=> Recover Client Implementation

pkg/plugins/gateway/algorithms/prefix_cache_preble.go
feat: make preble configurable and rename file
=> feat: make preble configurable and rename

samples/deepseek-r1/README.md, samples/deepseek-r1/deepseek-r1-tcp.yaml
This is a follow up of https://github.com/vllm-project/vllm/issues/17006#issuecomment-2889251888
User do not have RDMA resources can use TCP setup
---
<details>
<ul>
<li><code>[CI]</code>: Changes to build process or …
=> [Misc] Add deepseek-r1 tp8 pp2 example

README.md
Update the recent events and slides
---
<details>
<ul> …
=> [Misc] Update the latest news in README.md

python/aibrix_kvcache/aibrix_kvcache/envs.py, python/aibrix_kvcache/aibrix_kvcache/l2/connectors/infinistore.py, python/aibrix_kvcache/aibrix_kvcache/transport/__init__.py, python/aibrix_kvcache/aibrix_kvcache/transport/rdma.py, python/aibrix_kvcache/poetry.lock, python/aibrix_kvcache/pyproject.toml
- add RDMA auto-detection
- enable RDMA auto-detection in InfiniStore
---
<details>
<ul> …
=> [Feature] Add RDMA auto-detection for kvcache

benchmarks/generator/dataset_generator/synthetic_prefix_sharing_dataset.py, benchmarks/generator/workload_generator/README.md, benchmarks/generator/workload_generator/utility.py, docs/source/features/benchmark-and-generator.rst
This PR fixes bug in dataset generator, typo in doc. And adding a utility tool that helps merging workload files.
=> Multiple fixes and adding workload merging tool

config/manager/manager.yaml, pkg/controller/modelrouter/modelrouter_controller.go
Resolves: #1207 #1176
---
<details>
<ul> …
=> Add configurable httproute timeout

test/e2e/util.go
Replace the for loop in validateAllPodsAreReady with Kubernetes'
wait.PollUntilContextTimeout to improve reliability and readability. 
Resolves: https://github.com/vllm-project/aibrix/issues/1206
fix: https://github.com/vllm-project/aibrix/issues/1206
---
<details>
<p>Your PR title should start with one of these prefixes to indicate the nature of …
=> [Bug] fix(e2e flaky): replace for-loop with wait.PollUntilContextTimeout in validateAllPodsAreReady

docs/source/community/community.rst
Add maintainer guidelines
---
<details>
<ul>
<li><code>[API]</code>: Modifications …
=> [Doc] Add maintainer guidelines and contributor promotion criteria

samples/distributed/fleet-two-node.yaml
As stated in the [document](https://aibrix.readthedocs.io/latest/features/multi-node-inference.html#vllm-version), the example code cannot run multi node inference tasks, which will cause confusion for new users
Resolves: #1013
---
<details>
<ul> …
=> [Docs]fix: example docs error

pkg/controller/stormservice/stormservice_controller.go, pkg/controller/stormservice/sync.go
make sure the default type is configured to avoid errors
Resolves: part of https://github.com/vllm-project/aibrix/issues/1252#issuecomment-3041208488
---
<details>
<ul> …
=> Set Storm Service default update strategy

docs/source/designs/aibrix-kvcache-offloading-framework.rst, python/aibrix_kvcache/aibrix_kvcache/envs.py
Describe env vars used by kvcache.
---
<details>
<ul> …
=> [Doc] KVCache: add section for env vars

python/aibrix_kvcache/CMakeLists.txt, python/aibrix_kvcache/aibrix_kvcache/_custom_ops.py, python/aibrix_kvcache/setup.py
Change cuda kernel's namespace to avoid conflicts with vLLM's.
---
<details>
<ul> …
=> [Fix] KVCache: change cuda kernel's namespace

docs/source/designs/aibrix-kvcache-offloading-framework.rst, python/aibrix_kvcache/aibrix_kvcache/__init__.py, python/aibrix_kvcache/aibrix_kvcache/cache_hashable.py, python/aibrix_kvcache/aibrix_kvcache/cache_manager.py, python/aibrix_kvcache/aibrix_kvcache/envs.py, python/aibrix_kvcache/aibrix_kvcache/l1/l1_cache.py, python/aibrix_kvcache/aibrix_kvcache/l2/key_builders/hex_key_builder.py, python/aibrix_kvcache/aibrix_kvcache/l2/key_builders/key_builder.py, python/aibrix_kvcache/aibrix_kvcache/l2/key_builders/raw_key_builder.py, python/aibrix_kvcache/aibrix_kvcache/l2/key_builders/rolling_hash_key_builder.py, python/aibrix_kvcache/aibrix_kvcache/l2/key_builders/simple_hash_key_builder.py, python/aibrix_kvcache/aibrix_kvcache/l2/l2_cache.py, python/aibrix_kvcache/aibrix_kvcache/l2/marshallers/tensor_serializer.py, python/aibrix_kvcache/aibrix_kvcache/memory/allocator.py, python/aibrix_kvcache/aibrix_kvcache/metrics.py, python/aibrix_kvcache/tests/test_cache_manager.py, python/aibrix_kvcache/tests/test_cache_ops.py, python/aibrix_kvcache/tests/test_key_builder.py, python/aibrix_kvcache/tests/test_l1cache.py, python/aibrix_kvcache/tests/test_l2cache.py, python/aibrix_kvcache/tests/test_memory_region.py
- Introduce TokenListView to avoid using list slicing which involves memory copy
- Memorize key building results to avoid duplicate computing
- Refine key builder benchmarks and change default key builder to the RollingHashKeyBuilder which delievers the best performance among all built-in key builders based on the benchmarking result
---
<details>
<p>Your PR title should start with …
=> [Feature] KVCache: optimize token list iteration and key building

python/aibrix_kvcache/aibrix_kvcache/cache_manager.py, python/aibrix_kvcache/aibrix_kvcache/memory/allocator.py, python/aibrix_kvcache/tests/test_cache_manager.py, python/aibrix_kvcache/tests/test_cache_ops.py, python/aibrix_kvcache/tests/test_eviction_policies.py, python/aibrix_kvcache/tests/test_l1cache.py, python/aibrix_kvcache/tests/test_l2cache.py, python/aibrix_kvcache/tests/test_memory_region.py, python/aibrix_kvcache/tests/test_tensor_pool_allocator.py
Use a light-weight allocator if using compact laytout.
---
<details>
<ul> …
=> [Feature] KVCache: optimize allocator for compact layout

python/aibrix_kvcache/requirements/core.txt, python/aibrix_kvcache/requirements/test.txt
Fix requirements.
---
<details>
<ul> …
=> [Fix] KVCache: fix requirements

pkg/controller/stormservice/revision.go, pkg/controller/stormservice/revision_test.go, pkg/controller/stormservice/utils.go, pkg/controller/stormservice/utils_test.go, pkg/controller/util/patch/json_patch_test.go
UT coverage improvement
Resolves: part of https://github.com/vllm-project/aibrix/issues/1264
---
<details>
<ul> …
=> Improve UT coverage for stormservice controller

python/aibrix_kvcache/integration/vllm/vllm_v0.9.1-aibrix-kvcache.patch
- add vLLM V1 connector integration
- update vLLM V0 connector integration
---
<details>
<ul> …
=> [Integration] vLLM V1 Connector integration

.github/workflows/docker-push-images.yml
The pull request disables `docker-push-images` workflow in forked repositories.
---
<details>
<ul> …
=> [CI] Disable docker push images workflow in forked repositories

docs/source/designs/aibrix-stormservice.rst, docs/source/index.rst
add docs 
Resolves: part of https://github.com/vllm-project/aibrix/issues/1265
---
<details>
<ul> …
=> [Docs] Update stormservice docs and link to index page

pkg/cache/cache_metrics.go
In the current cache_metrics.go, the port for the metrics URL is hardcoded as 8000. I’ve modified it to dynamically use the value specified in the "model.aibrix.ai/MetricPort" annotation instead. The reason for not using "model.aibrix.ai/port" is that the HTTP proxy port may differ from the metrics collection port.
Resolves: none
---
<details>
<p>Your PR title should start with one of these prefixes to indicate the …
=> [feat] Support dynamic metrics port via model.aibrix.ai/metric-port label

pkg/plugins/gateway/queue/simple_queue.go
This PR fixes the out-of-index error for the simple queue implementation by:
1. Expand more space to avoid an out-of-index error on Enqueue.
2. Double-check the dequeue cursor outdating on Dequeue.
3. Correctly estimate the used space using enqueueCursor instead of triggerCursor.
Resolves: #1284
---
<details>
<ul> …
=> [Bug] Fix simple queue out of index error in unit test.

python/aibrix_kvcache/aibrix_kvcache/l2/connectors/infinistore.py
Enable connection pool for InfiniStore connector if TCP transport is used.
---
<details>
<ul> …
=> [Fix] KVCache: InfiniStore connector w/ TCP

.github/workflows/docker-push-images.yml
Sequential build will take 1hr to finish. Change to parallel mode to accelerate the build job
Resolves: [#[Insert issue number(s)]](https://github.com/vllm-project/aibrix/issues/1089#issuecomment-3111956271)
---
<details>
<ul> …
=> [CI] Enable multi-arch parallel build

pkg/plugins/gateway/algorithms/pd_disaggregation.go, pkg/plugins/gateway/gateway.go, pkg/plugins/gateway/gateway_req_body.go, pkg/plugins/gateway/gateway_req_body_test.go, pkg/plugins/gateway/gateway_req_headers.go, pkg/types/router_context.go
=> [feat] Add prefill-decode disaggregation support in aibrix router

config/dependency/kuberay-operator/kustomization.yaml, config/overlays/release/kustomization.yaml, config/overlays/vke/default/kustomization.yaml, config/standalone/distributed-inference-controller/kustomization.yaml, development/tutorials/distributed/README.md, hack/release/sync-dependency-images.sh
Address https://github.com/vllm-project/aibrix/issues/1094
Provides multi-arch kuberay-operator and bump the images to customized version.
Note: 
1. Earlier we use `quay.io/kuberay/operator` which may encounter issues. We should always use customized version with commit https://github.com/Yicheng-Lu-llll/kuberay/commit/91e1c26fbf1fc0f505ff7d16b70cf8228ed62ec4 from @Yicheng-Lu-llll 
2. Make up the last piece for arm support https://github.com/vllm-project/aibrix/issues/1089
Steps to build the image `aibrix/kuberay-operator:v1.2.1-patch-20250726`
```
docker buildx create --use --name multiarch-builder --driver docker-container
docker buildx inspect --bootstrap
docker buildx use multiarch-builder
docker run --rm --privileged tonistiigi/binfmt --install all
docker buildx inspect
git clone …
```
=> [CI] rebuilt kuberay operator with multi-arch support

.github/workflows/release-build.yaml, python/aibrix_kvcache/pyproject.toml, python/aibrix_kvcache/requirements/build.txt
=> [Fix] KVCache: fix release workflow

test/regression/v0.4.0/multi-engine/sglang-llama-8b.yaml, test/regression/v0.4.0/multi-engine/vllm-llama-8b.yaml, test/regression/v0.4.0/sglang/qwen-8b/aibrix-router.yaml, test/regression/v0.4.0/sglang/qwen-8b/sglang-router-cache.yaml, test/regression/v0.4.0/sglang/qwen-8b/sglang-router-random.yaml
Add experiment yamls
Resolves: part of https://github.com/vllm-project/aibrix/issues/1336
---
<details>
<ul> …
=> Add initial v0.4.0 regression test yamls

samples/disaggregation/vllm/1p1d.yaml, samples/disaggregation/vllm/README.md, samples/disaggregation/vllm/pool.yaml, samples/disaggregation/vllm/replica.yaml, samples/disaggregation/vllm/router.yaml
Add vLLM disaggregation samples 
---
<details>
<ul> …
=> [Misc] Add vLLM disaggregation samples

.github/workflows/release-build.yaml
=> [Fix] KVCache: fix no-space-left issue of release-build action

dist/chart/templates/controller-manager/deployment.yaml, dist/chart/values.yaml, dist/chart/vke.yaml
Fix the controller-manager start up issue.
Resolves: https://github.com/vllm-project/aibrix/issues/1364
---
<details>
<ul> …
=> [Fix] Correct default Helm values for health check port

test/regression/v0.4.0/sglang/qwen-32b/sglang-router-cache.yaml, test/regression/v0.4.0/sglang/qwen-32b/sglang-router-random.yaml, test/regression/v0.4.0/sglang/qwen-8b/sglang-router-1p1d-tp2.yaml, test/regression/v0.4.0/sglang/qwen-8b/sglang-router-1p1d.yaml, test/regression/v0.4.0/sglang/qwen-8b/sglang-router-4p3d.yaml, test/regression/v0.4.0/sglang/qwen-8b/sglang-router-cache.yaml, test/regression/v0.4.0/sglang/qwen-8b/sglang-router-random.yaml
1. make sure label are not same across experiments
2. fix sglang router cache-aware policy issue https://github.com/vllm-project/aibrix/issues/1351
---
<details>
<ul>
<li><code>[CI]</code>: Changes to build process or …
=> [Misc] Update v0.4.0 regression benchmark yamls

pkg/cache/build_verification_zmq_test.go, pkg/cache/cache_init_test.go, pkg/plugins/gateway/algorithms/prefix_cache_metrics_test.go, pkg/plugins/gateway/algorithms/prefix_cache_new_test.go, pkg/plugins/gateway/algorithms/prefix_cache_test.go
Resolves: Address https://github.com/vllm-project/aibrix/issues/1378
---
<details>
<ul>
<li><code>[Docs]</code>: …
=> [fix] Use t.Setenv to resolve racing problem

docs/source/features/gateway-plugins.rst, pkg/plugins/gateway/algorithms/README.md
=> [Doc] Add documentation for pd routing

pkg/cache/cache_metrics.go, pkg/cache/informers.go, pkg/cache/kv_event_manager_zmq.go, pkg/cache/kv_event_manager_zmq_test.go, pkg/constants/model.go, pkg/controller/kvcache/backends/vineyard.go, pkg/controller/modeladapter/modeladapter_controller.go, pkg/controller/modeladapter/resources_test.go, pkg/controller/modelrouter/modelrouter_controller.go, pkg/plugins/gateway/algorithms/pd_disaggregation.go, pkg/plugins/gateway/algorithms/prefix_cache.go, pkg/plugins/gateway/algorithms/prefix_cache_new_test.go, pkg/plugins/gateway/algorithms/tokenizer_pool.go, pkg/plugins/gateway/algorithms/tokenizer_pool_test.go, pkg/utils/pod.go, pkg/utils/pod_test.go, test/e2e/model_adapter_test.go
Add pkg/constants/model.go with
```go
ModelLabelName = "model.aibrix.ai/name"
ModelLabelEngine = "model.aibrix.ai/engine"
ModelLabelMetricPort = "model.aibrix.ai/metric-port"
ModelLabelPort = "model.aibrix.ai/port"
```
All these strings are replaced with `constants.ModelLabel*`.
=> Replace some hard-coded strings with pkg/constants/model.go 

.github/workflows/release-build.yaml
resolve the build failures
Resolves: related https://github.com/vllm-project/aibrix/issues/1388
---
<details>
<ul> …
=> [CI] Install poetry-dynamic-versioning plugin in release workflow

config/webhook/manifests.yaml, dist/chart/templates/webhook/webhooks.yaml, test/integration/webhook/kvcache_webhook_test.go
=> [Bug] fix: kvcache_webhook in integration test and webhook config

pkg/plugins/gateway/algorithms/pd_disaggregation.go, pkg/plugins/gateway/algorithms/pd_disaggregation_test.go
P/D prefix cache is not working well for workloads do not have cache hit, we need to improve this to adapt to normal workloads
before 
```
============ Serving Benchmark Result ============
Successful requests:                     200
Benchmark duration (s):                  206.02
Total input tokens:                      1599483
Total generated tokens:                  40000
Request throughput (req/s):              0.97
Output token throughput (tok/s):         194.16
Total Token throughput (tok/s):          7957.99
---------------Time to First Token----------------
Mean TTFT (ms):                          2882.46
Median TTFT (ms):                        2621.65
P95 TTFT (ms):                           4814.23
-----Time per Output Token (excl. 1st token)------
Mean TPOT (ms): …
```
=> Use random as fallback if cache miss in P/D router

pkg/plugins/gateway/algorithms/pd_disaggregation.go, pkg/plugins/gateway/algorithms/pd_disaggregation_test.go
This reverts commit 42cfab82520479b5f487aa37bf5771cb825be53d.
---
<details>
<ul> …
=> Revert "Use random as fallback if cache miss in P/D router (#1393)"

config/overlays/release/kustomization.yaml, config/overlays/vke/default/kustomization.yaml, config/standalone/autoscaler-controller/kustomization.yaml, config/standalone/distributed-inference-controller/kustomization.yaml, config/standalone/kv-cache-controller/kustomization.yaml, config/standalone/model-adapter-controller/kustomization.yaml, config/standalone/stormservice-controller/kustomization.yaml, dist/chart/Chart.yaml, dist/chart/vke.yaml, samples/disaggregation/vllm/1p1d.yaml, samples/disaggregation/vllm/pool.yaml, samples/disaggregation/vllm/replica.yaml, samples/quickstart/pd-model.yaml, test/regression/v0.4.0/vllm/1p1d.yaml
=> Cut release v0.4.0

config/webhook/manifests.yaml, pkg/webhook/kvcache_webhook.go
Resolves: https://github.com/vllm-project/aibrix/issues/1408#issuecomment-3162530114
---
<details>
<ul> …
=> [Bug] fix webhook config output when using make manifests

python/aibrix_kvcache/aibrix_kvcache/__init__.py, python/aibrix_kvcache/aibrix_kvcache/cache_handle.py, python/aibrix_kvcache/aibrix_kvcache/cache_manager.py, python/aibrix_kvcache/aibrix_kvcache/envs.py, python/aibrix_kvcache/aibrix_kvcache/l1/l1_cache.py, python/aibrix_kvcache/aibrix_kvcache/l2/connectors/connector.py, python/aibrix_kvcache/aibrix_kvcache/l2/connectors/hpkv.py, python/aibrix_kvcache/aibrix_kvcache/l2/connectors/infinistore.py, python/aibrix_kvcache/aibrix_kvcache/l2/connectors/mock.py, python/aibrix_kvcache/aibrix_kvcache/l2/connectors/pris.py, python/aibrix_kvcache/aibrix_kvcache/l2/l2_cache.py, python/aibrix_kvcache/aibrix_kvcache/l2/placement/placement.py, python/aibrix_kvcache/aibrix_kvcache/memory/allocator.py, python/aibrix_kvcache/aibrix_kvcache/memory/external_memory_region.py, python/aibrix_kvcache/aibrix_kvcache/memory/memory_region.py, python/aibrix_kvcache/aibrix_kvcache/spec.py, python/aibrix_kvcache/tests/conftest.py, python/aibrix_kvcache/tests/test_cache_handle.py, python/aibrix_kvcache/tests/test_cache_manager.py, python/aibrix_kvcache/tests/test_l1cache.py, python/aibrix_kvcache/tests/test_l2cache.py, python/aibrix_kvcache/tests/test_memory_region.py
- GDR support APIs
- UTs for GDR cache handle and GDR related APIs
---
<details>
<ul> …
=> [Feature] KVCache: support GDR

dist/chart/Chart.yaml
Enhance Chart.yaml metadata with comprehensive information
- Replace generic description with detailed feature overview
- Remove placeholder icon URL, add home URL and repo link
- Add comprehensive keywords for discoverability and category annotation
Resolves: part of https://github.com/vllm-project/aibrix/issues/1413
---
<details>
<p>Your PR title should start with one of these prefixes to indicate the nature of the …
=> [Misc]: Enhance Chart.yaml metadata with comprehensive information

samples/disaggregation/vllm/1p1d.yaml, samples/disaggregation/vllm/pool.yaml, samples/disaggregation/vllm/replica.yaml, samples/disaggregation/vllm/router.yaml, test/regression/v0.4.0/benchmark-client.yaml, test/regression/v0.4.0/multi-engine/vllm-llama-8b.yaml
This PR updates vllm PD disaggregation images used by all deployment files.
=> [misc] Update vLLM PD disaggregation image

pkg/controller/stormservice/sync.go
=> [Misc] remove unuseless event

test/regression/v0.4.0/configs/sglang-disagg-base.yaml, test/regression/v0.4.0/configs/sglang-non-disagg-base.yaml, test/regression/v0.4.0/configs/vllm-non-disagg-base.yaml, test/regression/v0.4.0/templates/sglang-disaggregated.yaml, test/regression/v0.4.0/templates/sglang-non-disaggregated.yaml, test/regression/v0.4.0/templates/vllm-disaggregated.yaml, test/regression/v0.4.0/templates/vllm-non-disaggregated.yaml
there're some configuration errors. I fix them in this PR
---
<details>
<ul> …
=> [Misc] fix regression test manifests

python/aibrix_kvcache/aibrix_kvcache/cache_manager.py
=> [Bug] KVCache: fix max seq len support

python/aibrix_kvcache/aibrix_kvcache/metrics.py, python/aibrix_kvcache/pyproject.toml, python/aibrix_kvcache/setup.py
Resolves: #1452
---
<details>
<ul> …
=> [Misc] KVCache bugfixes cherry-picks for v0.4.1

python/aibrix_kvcache/integration/vllm/vllm_v0.9.1-aibrix-kvcache.patch
Cherry picks from #1446 and #1473
Resolves: #1452 
---
<details>
<ul> …
=> KVCache integration cherry picks

config/overlays/release/kustomization.yaml, config/overlays/vke/default/kustomization.yaml, config/standalone/autoscaler-controller/kustomization.yaml, config/standalone/distributed-inference-controller/kustomization.yaml, config/standalone/kv-cache-controller/kustomization.yaml, config/standalone/model-adapter-controller/kustomization.yaml, config/standalone/stormservice-controller/kustomization.yaml, dist/chart/Chart.yaml, dist/chart/vke.yaml
=> Cut release v0.4.1 against release-0.4

docs/source/getting_started/installation/installation.rst, docs/source/getting_started/installation/lambda.rst, docs/source/getting_started/quickstart.rst, samples/volcano-engine/README.md
Resolves: https://github.com/vllm-project/aibrix/issues/1452
---
<details>
<ul>
<li><code>[API]</code>: Modifications …
=> Update installation guidance for v0.4.1

pkg/plugins/gateway/algorithms/least_request_test.go
=> add least_request_test

python/aibrix/aibrix/downloader/s3.py, python/aibrix/tests/downloader/test_downloader_s3.py
- Added detailed error handling for AWS credential issues, including specific messages for NoCredentialsError, CredentialRetrievalError, and ClientError.
- Improved logging for IRSA authentication failures, providing troubleshooting steps and environment details.
- Updated the S3Downloader to support scenarios where no AWS credentials are provided, defaulting to IRSA or the default credential chain.
- Refactored tests to validate the new error handling and IRSA support functionality.
---
<details>
<p>We …
=> [Misc] Enhance S3Downloader error handling and IRSA support

pkg/controller/podset/podset_controller.go, pkg/controller/roleset/podset_rollsyncer.go
=> Fix missing FQDN and reuse hash func from syncer

docs/source/getting_started/faq.rst
Add `Using NodePort to Expose the Gateway API` section
Resolves: #1281
---
<details>
<ul> …
=> [Docs] Add `Using NodePort to Expose the Gateway API` section

pkg/controller/modeladapter/modeladapter_controller.go, pkg/controller/modelrouter/modelrouter_controller.go, test/integration/controller/roleset_test.go, test/integration/controller/suit_test.go, test/utils/validation/roleset.go, test/utils/wrapper/roleset.go
part of: https://github.com/vllm-project/aibrix/issues/1430
---
<details>
<ul> …
=> add rolset integration test

pkg/cache/cache_init.go, pkg/plugins/gateway/algorithms/least_gpu_cache_test.go
add unit test for leastGpuCacheRouter
a part of #1485 
---
<details>
<ul> …
=> [Misc] test: add unit test for leastGpuCacheRouter

pkg/controller/roleset/podset_rollsyncer.go, pkg/controller/roleset/sync.go
=> [Bug] fix count ready podset condition

.gitignore
Ignore `setuptools-scm` generated `_version.py` file.
While following the quick-start guide at [https://github.com/vllm-project/aibrix/blob/main/python/aibrix_kvcache/README.md#quick-start](https://github.com/vllm-project/aibrix/blob/main/python/aibrix_kvcache/README.md#quick-start), I found an untracked `_version.py` file was generated.
---
<details> …
=> [Misc]chore: ignore auto-generated ` _version.py` file

pkg/plugins/gateway/algorithms/throughput_test.go
add unit test for throughputRouter
a part of #1485 
---
<details>
<ul> …
=> [Misc] test: add unit test for throughputRouter

pkg/plugins/gateway/algorithms/least_load_test.go
add test for least_load
Part of: #1485 
---
<details>
<ul> …
=> [MISC]: add test for least_load

test/integration/controller/podset_test.go, test/integration/controller/stormservice_test.go, test/utils/validation/podset.go, test/utils/validation/stormservice.go, test/utils/wrapper/stormservice.go
part of: https://github.com/vllm-project/aibrix/issues/1430
---
<details>
<ul> …
=> [Misc]: add stormservice integration test

.github/workflows/installation-tests.yml, development/app/config/templates/deployment/deployment.yaml, python/aibrix/poetry.lock, python/aibrix/pyproject.toml, test/run-e2e-tests.sh
Resolves: https://github.com/vllm-project/aibrix/issues/1554
---
<details>
<ul>
<li><code>[API]</code>: Modifications …
=> [CI] fix vllm-mock runtime sidecar startup issue

python/aibrix_kvcache/aibrix_kvcache/__init__.py, python/aibrix_kvcache/aibrix_kvcache/cache_args.py, python/aibrix_kvcache/aibrix_kvcache/cache_hashable.py, python/aibrix_kvcache/aibrix_kvcache/cache_manager.py, python/aibrix_kvcache/aibrix_kvcache/l1/l1_cache.py, python/aibrix_kvcache/aibrix_kvcache/l2/key_builders/hex_key_builder.py, python/aibrix_kvcache/aibrix_kvcache/l2/key_builders/key_builder.py, python/aibrix_kvcache/aibrix_kvcache/l2/key_builders/raw_key_builder.py, python/aibrix_kvcache/aibrix_kvcache/l2/key_builders/rolling_hash_key_builder.py, python/aibrix_kvcache/aibrix_kvcache/l2/key_builders/simple_hash_key_builder.py, python/aibrix_kvcache/aibrix_kvcache/l2/l2_cache.py, python/aibrix_kvcache/aibrix_kvcache/memory/allocator.py, python/aibrix_kvcache/aibrix_kvcache/metrics.py, python/aibrix_kvcache/tests/conftest.py, python/aibrix_kvcache/tests/test_cache_manager.py, python/aibrix_kvcache/tests/test_eviction_policies.py, python/aibrix_kvcache/tests/test_l1cache.py, python/aibrix_kvcache/tests/test_l2cache.py, python/aibrix_kvcache/tests/test_memory_region.py
- KVCache API supports block hashes
- Change parameter name `tokens` to `query` in all APIs to improve readability
---
<details>
<ul> …
=> [API] KVCache: support block hashes

development/app/config/mock/api-key-patch.yaml
```yaml
➜  ~ kubectl apply -f deploy.yaml
The Deployment "mock-llama2-7b" is invalid: spec.template.metadata.labels: Invalid value: map[string]string(nil): `selector` does not match template `labels`
```
---
<details>
<p>Your PR title should start with one of these prefixes to indicate the nature of the …
=> fix(deploy): add missing labels to pod template

pkg/controller/podautoscaler/hpa_resources.go
Add multi-metrics-source support for hpa. This enable pod-autoscaler-controller to make a hpa with more than one metrics.
Resolves: #[1565](https://github.com/vllm-project/aibrix/issues/1565)
---
<details>
<ul>
<li><code>[CI]</code>: Changes to build …
=> Add multi-metrics-source-support for hpa

test/integration/controller/suit_test.go
Suppress massive controller logs, if user need to debug it, user can specific the right log level
---
<details>
<ul>
<li><code>[Docs]</code>: Updates …
=> [Misc] Suppress info logs in integration tests

Makefile
same as title. this is a follow up of https://github.com/vllm-project/aibrix/pull/1556/files
Resolves: https://github.com/vllm-project/aibrix/issues/1553
---
<details>
<ul> …
=> [CI] Exclude integration tests from race condition test

pkg/controller/modelrouter/modelrouter_controller.go
- optimize deleteReferenceGrant with label selector
---
<details>
<ul> …
=> [Mics]: optimize deleteReferenceGrant with label selector in ModelRouter controller

python/aibrix/aibrix/downloader/s3.py, python/aibrix/aibrix/downloader/tos.py, python/aibrix/tests/downloader/test_downloader_s3.py
This PR adds fixes for tos client to download nested directories
Related to #1509
=> Add recursive download for tos v2/s3 client

pkg/controller/kvcache/kvcache_controller.go
The current scenario requires mapping Pod events to their associated KVCache resources
=> Use EnqueueRequestsFromMapFunc for KVCache controller

.github/workflows/python-aibrix-kvcache-tests.yml, python/aibrix_kvcache/aibrix_kvcache/cache_manager.py, python/aibrix_kvcache/aibrix_kvcache/spec.py
Support specifying max_num_batched_tokens in kvcache config, which will be used to determine the sizes of internal buffers.
---
<details>
<ul> …
=> [Chore] KVCache: add max_num_batched_tokens config

pkg/controller/podautoscaler/podautoscaler_controller.go
Part of: part of #1422
---
<details>
<ul> …
=> [Bug] podautoscaler: only emit when replica count changes
